### ISSUE TITLE
Request for Addition of Data Encryption Feature

### ISSUE THREAD

**Issue by DemonAngeX2** [imagegenius/docker-immich#111]
Dear Development Team,

I hope this message finds you well. I am writing to request the addition of a crucial feature to the Immich application, specifically the implementation of data encryption for user photos and videos.

As a multi-user application that allows users to store their personal media on your server, it is essential to prioritize the security and privacy of their data. By introducing data encryption, you can provide users with an added layer of protection, ensuring that their photos and videos are securely stored and inaccessible to unauthorized individuals.

Implementing data encryption would involve encrypting user data before it is uploaded to the server and decrypting it when accessed by the authorized user. This approach would significantly enhance the confidentiality and integrity of the stored media, mitigating concerns regarding unauthorized access.

I understand that implementing such a feature may require significant development resources and considerations. However, it would be highly beneficial to both the users and the reputation of the Immich application. Data privacy and security are critical aspects of any modern application, and the addition of data encryption would position Immich as a trusted platform that prioritizes user privacy.

Thank you for considering my request. I believe that by implementing data encryption, Immich can provide a more secure and reliable service, fostering trust among its users. If there are any further details or discussions required, please do not hesitate to reach out.

Sincerely,
Alex

**Comment by hydazz** [comment]
please forward your request to the geniuses at https://github.com/immich-app/immich

this is just a container for immich-app/immich
