### ISSUE TITLE
how do i make immich use gpu

### ISSUE THREAD

**Issue by kubbur** [imagegenius/docker-immich#117]
sorry for the noobness, but i dont get where to put "--gpus=all"
would it be possible to get a small guide please

**Comment by hydazz** [comment]
do you use docker compose, unraid or cli (docker run...)?

**Comment by kubbur** [comment]
Ah sorry, I'm using the default unraid docker environment ![image](https://github.com/imagegenius/docker-immich/assets/816497/72baf6a0-c66c-4e10-9526-45a07f6a5a11)

**Comment by hydazz** [comment]
enable advanced view and put it in `Extra Parameters`

![image](https://github.com/imagegenius/docker-immich/assets/53986978/11b08b03-c232-4219-a92c-cbd42caa7476)

**Comment by kubbur** [comment]
ah ofc, thanks
