### ISSUE TITLE
noml version is broken - Config validation error: "TYPESENSE_API_KEY" is required

### ISSUE THREAD

**Issue by lnxsnw** [imagegenius/docker-immich#127]
The noml version is broken, asking for a "TYPESENSE_API_KEY". The [ci result](https://ci-tests.imagegenius.io/immich/latest-noml/index.html) and its logs is the same as mine.

Tried different latest versions of the noml packages, same error output both in web and logs.
Running on Raspberry Pi 4B 8GB.

**Comment by martabal** [comment]
Error found, thanks for the report !
