### ISSUE TITLE
After updating the image, the first run on "chown" still takes more than 3 minutes.

### ISSUE THREAD

**Issue by rexzhang** [imagegenius/docker-immich#138]
Is there any way to solve it? It will be reproduced when a new container is created.

Ref:
#125 #112

**Comment by martabal** [comment]
Can you help us identify which folders takes so much time ? https://github.com/imagegenius/docker-immich/pull/124#issuecomment-1615868312

**Comment by rexzhang** [comment]
```
time find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +

real    0m0.045s
user    0m0.009s
sys     0m0.036s
```

**Comment by rexzhang** [comment]
It will be reproduced when a new container is created.

**Comment by hydazz** [comment]
The same thing happens when you use `find`, the time should not change, even if the files have the same permissions
