### ISSUE TITLE
Getting error when enabling cuda enabled - python error

### ISSUE THREAD

**Issue by travisboss** [imagegenius/docker-immich#141]
```
For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/immich/machine-learning/app/main.py", line 11, in <module>
    from .config import settings
  File "/app/immich/machine-learning/app/config.py", line 3, in <module>
    from pydantic import BaseSettings
  File "/config/cuda-venv/lib/python3.11/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/cuda-venv/lib/python3.11/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
```

I get the same error using `immich-cuda-node`, verified `sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi` that nvidia-smi is running fine.

**Comment by martabal** [comment]
Can confirm this issue, it seems you have to rollback to a previous pydantic version (1.9.0 seems to work). The cpu version does not have this problem thanks to poetry. 

I see only two options for this problem : 
- maintaining our own dependencies with poetry or a requirements.txt file
- deprecating the custom cuda acceleration

What do you think @hydazz ?

**Comment by hydazz** [comment]
cant we install pydantic 1.9.0?

**Comment by martabal** [comment]
Yes but we have to precise it somewhere (with poetry or requirements.txt)

**Comment by hydazz** [comment]
> Yes but we have to precise it somewhere (with poetry or requirements.txt)

```
    pip install -U --no-cache-dir \
        aiocache \
        fastapi \
        insightface \
        numpy \
        onnxruntime \
        pydantic==1.9.0 \
        Pillow \
        scikit-learn \
        scipy \
        sentencepiece \
        sentence-transformers \
        torch \
        tqdm \
        transformers \
        uvicorn[standard]
```
https://github.com/imagegenius/docker-immich/blob/main/root/etc/s6-overlay/s6-rc.d/init-config-cuda/run?

**Comment by martabal** [comment]
Yep this works too, but it can lead to conflicts

**Comment by martabal** [comment]
@hydazz, just tried it and it shows new errors `ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' `

**Comment by travisboss** [comment]
@martabal at this time would it be best to disable cuda acceleration?

**Comment by martabal** [comment]
Yes probably until it's officially supported or this dependency error is solved upstream

**Comment by martabal** [comment]
Cuda acceleration is no longer supported
