### ISSUE TITLE
[BUG] Restarting container in Unraid results in re-downloading all the libraries

### ISSUE THREAD

**Issue by madhusudhanarya** [imagegenius/docker-immich#144]
The bug
When the Immich container is restarted in Unraid server, all the libraries gets re-downloaded. This happens every time Immich container is restarted which is not the expected behavior.

The OS that Immich Server is running on
Unraid 6.11.5

Reproduction steps
1. Search "Immich" in Unraid Community Applications, click on "Install"
2. Fill the Immich installation template and click on "Apply"
3. Wait for the container to spin up. Take ~5-10 mins to download the libraries and start the server
4. Stop/start or Restart the Immich container
5. During the restart, all libraries gets re-downloaded again. This happens every time Immich container is restarted.

https://github.com/immich-app/immich/issues/3264

**Comment by martabal** [comment]
Did you enable `CUDA_ACCELERATION` ?

**Comment by madhusudhanarya** [comment]
Yes, i have as I have a Nvidia GPU installed.

**Comment by martabal** [comment]
This is the desired behavior, we check at each start if the libraries are installed and up to date. Packages are too big (+5gB) to be included in the image.

**Comment by madhusudhanarya** [comment]
Ok. Is it possible to modify this behavior such that, libraries are checked once in X days or when manually requested by the user? this way, its possible to make use of Nvidia GPU without having to download the libraries every time the container is restarted. I have bunch of 4K videos which are getting converted by immich to lower resolution using CPU. Its taking time and occasionally causing timeout while opening immich.

**Comment by hydazz** [comment]
@martabal `if [ <previous> != <current> ]; then` ..., possible echo the version to a file in /config or is there somewhere else we can hide the previously installed version?

**Comment by martabal** [comment]
> @martabal `if [ <previous> != <current> ]; then` ..., possible echo the version to a file in /config or is there somewhere else we can hide the previously installed version?

We absolutely can. It would be even better to echo the date of the last update/install instead of the version. 
But with #141, IMO it's better to entirely disable machine-learning until it's officially supported. When it'll be supported we might even get a poetry.lock so It would be a lot easier to track and update pip packages only when required.

**Comment by martabal** [comment]
`CUDA_ACCELERATION` has been disabled until official support 😢
