### ISSUE TITLE
all the images taken vertically are rotated left by 90 degrees in webui in docker. 

### ISSUE THREAD

**Issue by MayurAgarkar** [imagegenius/docker-immich#147]
Hi, 

Since last update, all the images I have taken and uploaded from my mobile device and directly in my NAS, are rotated left by 90 degrees. 
Its super weird. in the Android Mobile app, on the phone which took the images, I am able to see images properly. 
But on another phone app and on docker webui, all the vertically taken images are rotated.

Plus, there is no way currently in webui to edit the image to rotate it back and make correct orientation. 
Can you pl help ! 
I have around 28000 images and more than 10k are rotated like this ! Not just latest but old images too. 

Attached a screenshot. 
![Screenshot 2023-07-21 at 10 19 13 AM](https://github.com/imagegenius/docker-immich/assets/10101518/2338e7d3-3114-4752-9d1e-f75569e1be78)

**Comment by martabal** [comment]
This sounds like this is an upstream issue. Please post it on the [immich repo](https://github.com/immich-app/immich/issues)
