### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Majestic7979** [imagegenius/docker-immich#150]
Not an issue - just a thank you. Works flawlessly for me. No bother whatsoever getting it to run. I have Redis and Postgres set up on another host, used Adminer to create the Postgres DB, smooth sailing afterwards. Please keep maintaining the image, you're doing a very useful job and helping a lot.

**Comment by martabal** [comment]
Thank you for your kind words, it's a pleasure to maintain this image, I'm not leaving anytime soon :smile:

**Comment by Majestic7979** [comment]
Very happy to hear and I'm sure everyone benefitting from your hard work will be too!
