### ISSUE TITLE
Container error when using `REDIS_SOCKET`

### ISSUE THREAD

**Issue by shiruken** [imagegenius/docker-immich#156]
Support for the `REDIS_SOCKET` environment variable was added in #154. However, the container is now throwing an error if the `REDIS_HOSTNAME` environment variable is not defined.

![image](https://github.com/imagegenius/docker-immich/assets/867617/7bbe6f2d-dff2-45e4-a3ee-74bda38e3566)

Image: `ghcr.io/imagegenius/immich:latest`
Build Version: `ImageGenius Version:- v1.71.0-ig159 Build-date:- 2023-08-03T22:12:20+10:00`

**Comment by martabal** [comment]
My bad, I mixed `&&` with `||`. I tested and confirm that #157 resolves it. Sorry for the trouble

**Comment by shiruken** [comment]
No worries! Just tested and it's working perfectly now.
