### ISSUE TITLE
Feature: choose external API URL

### ISSUE THREAD

**Issue by ikbenignace** [imagegenius/docker-immich#159]
I know this is a all in 1 docker, but I use traefik through easypanel, and I'm not able to add a stripprefix, which means I want to define a custom URL which I've already choosen. I point a url to  3001 and that url I want to use for the API.

So it would be nice to have a environment variable for this.

**Comment by martabal** [comment]
Indeed, we can't really do something with this image. I think we could change the api endpoint but not the url for the webui. 
https://github.com/immich-app/immich/discussions/1679

**Comment by ikbenignace** [comment]
Yea i thought with using IMMICH_API_URL_EXTERNAL, but it doesn't  do anything

**Comment by martabal** [comment]
`IMMICH_API_URL_EXTERNAL` is used when the server is hosted on a different server than the web service. It does not really make sense to use it for this image

**Comment by hydazz** [comment]
expose port `3001` or`3000` seperatly from the container and make a custom nginx config? or overwrite `/defaults/default.site` with a custom nginx config
