### ISSUE TITLE
Is the 1.72 image ready for NVIDIA transcoding?

### ISSUE THREAD

**Issue by Majestic7979** [imagegenius/docker-immich#160]
I have the Nvidia runtime, and I am running the 535 driver (latest).
It's working on other containers like Frigate for example. nvidia-smi shows this to be the case.
I'd like to enable HW transcoding as I have a GTX1080 in my server for just this kind of thing.
When I initially started using this container my video library required transcoding and my CPU ran at 99C for almost two days! Not healthy... the GPU would've done a much better job and cooler too.
If you have made the hwaccel.yml file available inside is it linked to any docker environment variables? I run my container using docker CLI not docker compose. Normally all I need to do is to add --gpus=all and --runtime=nvidia to a container to enable it to "see" the GPU. If it's ready to go please provide instructions on how to get this running.

Currently I do this to create and run the container:

```
docker create --name=immich --restart=unless-stopped --gpus=all -p 5456:8080 -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -e DB_HOSTNAME=x.x.x.x -e DB_USERNAME=xxxxxx -e DB_PASSWORD="xxxxxxxxxxxxxxxxx" -e DB_DATABASE_NAME=immich -e REDIS_HOSTNAME=x.x.x.x -e DISABLE_MACHINE_LEARNING=false -e DISABLE_TYPESENSE=false -e DB_PORT=5432 -e REDIS_PORT=6379  -v /home/user/docker/immich/config:/config -v /home/user/Pictures/originals:/photos -v /home/user/docker/immich/machine-learning:/config/machine-learning ghcr.io/imagegenius/immich:latest && docker start immich
```

**Comment by FrankRodelli** [comment]
Also hoping to get information on this. I used the same setup I use in other containers that make user of the GPU like frigate and emby and it seems to fail over to CPU transcoding

**Comment by hydazz** [comment]
it should work for transcoding, you might have to set `NVIDIA_DRIVER_CAPABILITIES=all`

and use `--gpus=all` or:
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

try uploading a video, and monitor `watch nvidia-smi` closely and see if ffmpeg tries to use the gpu, give it a quick shot and let us know how it goes

**Comment by hydazz** [comment]
I've gotten it working without any changes, just make sure to enable hardware acceleration in FFmpeg Settings in immich after enabling the gpu in docker

**Comment by FrankRodelli** [comment]
I use the container in unraid so compose is also not applicable to me. I did add the mentioned parameters/variables and I will report back when I test.

**Comment by FrankRodelli** [comment]
Seems to be working as expected! Here is what I did for anyone that is also using unraid. I'm not sure if all of it is necessary, but whatever. 

**Variables:** 
NVIDIA_DRIVER_CAPABILITIES=all
NVIDIA_VISIBLE_DEVICES=GPU-addff58f-ea13-7320-9a60-9efc4707ccf7
_(visible device should be set to your gpuid. It can be found in the nvidia driver section in settings after you've installed the nvidia driver package)_

**Extra Parameters:** 
--gpus=all --runtime=nvidia 



Logs should look like this: 
`[Nest] 777  - 08/07/2023, 4:13:18 AM     LOG [MediaService] Start encoding video 1d8f606b-107a-41b2-a6aa-7c000e8655dd {"inputOptions":["-init_hw_device cuda=cuda:0","-filter_hw_device cuda"],"outputOptions":["-vcodec h264_nvenc","-tune hq","-qmin 0","-g 250","-bf 3","-b_ref_mode middle","-temporal-aq 1","-rc-lookahead 20","-i_qfactor 0.75","-b_qfactor 1.1","-acodec aac","-movflags faststart","-fps_mode passthrough","-v verbose","-vf hwupload_cuda,scale_cuda=720:-2","-preset p1","-cq:v 23"],"twoPass":false}
[Nest] 777  - 08/07/2023, 4:13:21 AM     LOG [MediaService] Encoding success 1d8f606b-107a-41b2-a6aa-7c000e8655dd`

**Comment by Majestic7979** [comment]
We've got some confirmations so I'll go ahead and close the issue. Thanks all.
