### ISSUE TITLE
The web App is down, server totally unavailable and unrecoverable after uploading media to the server from iPhone.

### ISSUE THREAD

**Issue by niyazaki** [imagegenius/docker-immich#172]
Today after trying to update media from my iPhone to my server the app crashed. I then looked to the webapp on my computer and found that the webApp wasn't responding and then returned me a dialog with "ERROR 50X" not sure about the last digit. After restarting the container then restarting the host server, the webApp is totally black. I looked the last releases from this project and the original one and found that there were "breaking changes" I then updated the parameters in the docker config (pressing on the name of the docker container on docker tab on unraid) to replace "DISABLE_MACHINE_LEANRING" (and noticed the mispelled word) with the new "IMMICH_MACHINE_LEARNING_ENABLED", nothing changed. I then tried to update the param to "DISABLE_MACHINE_LEARNING" same result. I'm running out of troubleshooting solutions. Could you 

Installation :
Using Docker with Unraid on an intel processor with nvme ssd for caching and HDD for storage.

Here are all the logs I can find via the unraid webApp:
```
      method: 'get',
      url: 'http://127.0.0.1:3001/user/me',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /user/me HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer qqrSnnjQhcOiSXsXZz8dvml4rerbcoSa5kW0oywlGI\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: 127.0.0.1:3001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/user/me',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { statusCode: 500, message: 'Internal server error' }
  }
}
[Nest] 193  - 08/27/2023, 12:48:17 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:628:28)
    at Connection.emit (node:events:514:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12)
[Nest] 193  - 08/27/2023, 12:48:29 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:628:28)
    at Connection.emit (node:events:514:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [621]
```
Config :
Except redis and postgresql variables and path for storage variables I only have those 2 set up :
![image](https://github.com/imagegenius/docker-immich/assets/34636175/4d40d45e-9a37-427e-a647-44ed0d8ed785)

**Comment by hydazz** [comment]
@martabal 🤔

**Comment by niyazaki** [comment]
The error was probably a 500. Maybe 501/504. Sorry if you can tell me where to find the logs I can share them. Thank you for your help :)

**Comment by martabal** [comment]
It looks like your database is not running

**Comment by niyazaki** [comment]
@martabal thank you for your quick response.
I didn't change my pg14, redis nor immich config since I set it up (approx) a month ago. I didn't change the folder structure nor the disk settings since that time.

How can I prove or test that the connexion to db with the settings in Immich config are ok ? 

Here are the logs from my postgresql14 db:
`2023-08-18 06:02:17.655 CEST [1] LOG:  starting PostgreSQL 14.9 (Debian 14.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-08-18 06:02:17.656 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-18 06:02:17.656 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2023-08-18 06:02:17.666 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-18 06:02:17.680 CEST [27] LOG:  database system was shut down at 2023-08-18 06:01:15 CEST
2023-08-18 06:02:17.696 CEST [1] LOG:  database system is ready to accept connections

PostgreSQL Database directory appears to contain a database; Skipping initialization`

Redis:
`2720:C 27 Aug 2023 15:47:53.082 * DB saved on disk
2720:C 27 Aug 2023 15:47:53.082 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 0 MB
1:M 27 Aug 2023 15:47:53.169 * Background saving terminated with success
1:M 27 Aug 2023 15:52:54.057 * 100 changes in 300 seconds. Saving...
1:M 27 Aug 2023 15:52:54.058 * Background saving started by pid 2721
2721:C 27 Aug 2023 15:52:54.073 * DB saved on disk
2721:C 27 Aug 2023 15:52:54.073 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 0 MB
1:M 27 Aug 2023 15:52:54.159 * Background saving terminated with success
1:M 27 Aug 2023 15:57:55.019 * 100 changes in 300 seconds. Saving...
1:M 27 Aug 2023 15:57:55.019 * Background saving started by pid 2722
2722:C 27 Aug 2023 15:57:55.034 * DB saved on disk
2722:C 27 Aug 2023 15:57:55.034 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 0 MB
1:M 27 Aug 2023 15:57:55.120 * Background saving terminated with success`

**Comment by martabal** [comment]
If you use typesense (used for the search) and the machine-learning, you can completely remove `DISABLE_MACHINE_LEARNING` and `DISABLE_TYPESENSE` envs from your config. Can you restart Immich and provide the complete log ?

**Comment by niyazaki** [comment]
It's fixed now, thank you very much :).
