### ISSUE TITLE
Error: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"

### ISSUE THREAD

**Issue by someonewating** [imagegenius/docker-immich#176]
Hi there,

I'm running immich with redis in the container via `DOCKER_MODS=imagegenius/mods:universal-redis`. But I got `Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"` error. The webpage will be unreachable with `502 Bad Gateway` error code.

Previously, I ran redis in the container by compiling the docker image manually, and I never saw this kind of error. 

Besides, the issue will not appear everytime I access the webpage. Sometimes the `Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108"` error appears and I can't access the webpage, and after a few minutes, the error stops throwing and I can access the web suddenly.

Thank you in advance.

**Comment by martabal** [comment]
This error means you have an issue with typesense, not redis. You can try to delete the `typesense` folder in your `/config`

**Comment by someonewating** [comment]
HI. Yes I tried to delete the folder before, and it works. But after several minutes, I got the same error message again.

**Comment by martabal** [comment]
Since when do you have this issue ?

**Comment by someonewating** [comment]
I was using [](https://github.com/imagegenius/docker-immich/releases/tag/v1.67.2-ig151) for a long time, and it's ok for me. and recently I updated the server to the latest version, and I got this error.

**Comment by martabal** [comment]
Does your CPU support AVX?

**Comment by martabal** [comment]
Please note that when Immich starts you have to wait a few tens of seconds for Typesense to start too

**Comment by hydazz** [comment]
@someonewating try using the `:latest` tag, and when this error occurs again try run `nc -v -z 127.0.0.1 8108` to probe the typesense service, and see whether its up:
```
root@fa7a389b8980:/# nc -v -z 127.0.0.1 8108
localhost [127.0.0.1] 8108 (?) open
```
if you see no response (ie `nc` hangs) then typesense is the culprit else immich is playing games...

**Comment by someonewating** [comment]
> Does your CPU support AVX?

Yes, my computer supports AVX.

> try using the :latest tag, and when this error occurs again try run nc -v -z 127.0.0.1 8108 to probe the typesense service

I got this error. `localhost [127.0.0.1] 8108 (?) : Connection refused`

**Comment by hydazz** [comment]
does this error occur when you downgrade immich?

**Comment by someonewating** [comment]
> > BTW, I deployed immich on azure container app for a long time, but this is the first time I seen this error, it was perfect before.
> 
> does this error occur when you downgrade immich?

I haven't tried, but I have this error as soon as I upgraded immich to the latest version, I don't think azure changed their infrastructure. I'll try to downgrade and let you know the result.

**Comment by someonewating** [comment]
> 

Hi. You are right, I downgraded immich to a version that ran ok before, but I still got the same error, surprisingly. Thus, I think it's not the problem with immich itself. This is weird. Please let me know if you have any ideas about this situation. Thank you.

**Comment by hydazz** [comment]
> > 
> 
> 
> 
> Hi. You are right, I downgraded immich to a version that ran ok before, but I still got the same error, surprisingly. Thus, I think it's not the problem with immich itself. I can also run this version on my laptop with exactly same configuration. This is weird. Please let me know if you have any ideas about this situation. Thank you.

Are there any other logs to do with typesense in the console?

**Comment by someonewating** [comment]
> > > 
> > 
> > 
> > Hi. You are right, I downgraded immich to a version that ran ok before, but I still got the same error, surprisingly. Thus, I think it's not the problem with immich itself. I can also run this version on my laptop with exactly same configuration. This is weird. Please let me know if you have any ideas about this situation. Thank you.
> 
> Are there any other logs to do with typesense in the console?

No, the error is nothing different with the two versions. I can only suspect Azure changed something. Because like I said before, initially the error could disappear by itself after several minutes. But now it cannot disappear. I guess Azure changed their infrastructure with somehow canary release maybe. As Azure container app allocate computing resources to users dynamically based on the needs of the user program.

**Comment by hydazz** [comment]
monitor the logs, see if theres anything spamming the logs of the container, if you don't open the webui, it should be easy to see anything outlying
