### ISSUE TITLE
Immich container starts but then ECONNREFUSED errors in log - No WebUI

### ISSUE THREAD

**Issue by Tyree** [imagegenius/docker-immich#186]
I just had my unRAID server go down. I have it back up (had to replace RAM) and all containers are loading except for Immich. I am getting this error in the logs:
Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108
It's been spitting that out every 4 seconds for about 30 minutes now.
The database and photos share are intact and available. I see from the immich docs that 8108 is the Typesense host....Not sure what to do about that.

Any help is appreciated. Thanks!

**Comment by martabal** [comment]
Stop your immich container, delete the `typesense` folder in `/config` and restart your Immich container.

**Comment by Tyree** [comment]
That worked. Thank you.
