### ISSUE TITLE
Hardware Transcoding - Officially Supported

### ISSUE THREAD

**Issue by wjbeckett** [imagegenius/docker-immich#190]
Now that Hardware Transcoding is officially supported natively in Immich, will we see the options in the AIO image?

**Comment by martabal** [comment]
It's already supported. What gpu do you have ?

**Comment by wjbeckett** [comment]
Ah.
I have a RTX 3060.

What env vars do I need to use on-top of the --runtime=nvidia?

**Comment by martabal** [comment]
Ahah we had the same request a few hours ago, you can have a look at the setup shared here #189.

I will probably open a FR to add some documentation in the README
