### ISSUE TITLE
Add PaddleOCR to Immich

### ISSUE THREAD

**Issue by eagle470** [imagegenius/docker-immich#193]
Per this posted issue PaddleOCR seems to be the way to add OCR to the app. Can you roll this into your container?

https://github.com/immich-app/immich/issues/565

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/README.md

**Comment by martabal** [comment]
Immich does not support it, so we can't support OCR without forking it (and we really don't want to)
