### ISSUE TITLE
Crash since last update 

### ISSUE THREAD

**Issue by guim31** [imagegenius/docker-immich#195]
I use a reverse proxy to access my server. (swag on my Unraid machine).

Today I found out that my Immich mobile app did not work and I saw this message in the changelog of Immich : 
![image](https://github.com/imagegenius/docker-immich/assets/33096540/9f3c26ca-a949-45fd-8a09-a5bf9b73c76e)

My error message when I try to reach immich.mydomain.com : 
![image](https://github.com/imagegenius/docker-immich/assets/33096540/caa51af2-fd47-48bd-b8d6-e13db2cb4ab8)

Here is my nginx conf file : 

```server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name immich.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;


    location / {


        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.100.150;
        set $upstream_port 8282;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
```

Someone to help me ? I don't know how to do what Immich team tells me to do : 

> We removed a section from the default docker-compose.yml that passed the IMMICH_SERVER_URL and IMMICH_WEB_URL environment variables to immich-proxy. If your setup requires those, make sure you keep them passed through.

**Comment by martabal** [comment]
With this implementation you don't need to touch `IMMICH_SERVER_URL` or `IMMICH_WEB_URL`

**Comment by guim31** [comment]
Ok thanks, so what could have crashed my Immich install ? 
I can access my immich server on my local network without a problem.

**Comment by guim31** [comment]
Ok so a restart of my SWAG container did the job....
Thanks a lot for your time :)
