### ISSUE TITLE
noml version ignoring IMMICH_MACHINE_LEARNING_URL

### ISSUE THREAD

**Issue by traktuner** [imagegenius/docker-immich#199]
Hello,
I wanted to switch to the lightweight alpine noml image, since I have a more powerful remote server which handles ML via the 
IMMICH_MACHINE_LEARNING_URL
environment variable.
But the image just disables all ML funtions completely (jobs have a "disabled" icon). Is that by design, even if an external ML server is used?
Thank you!

**Comment by martabal** [comment]
You have two options:
- Set `IMMICH_MACHINE_LEARNING_URL` to your remote server ip:port and set `IMMICH_MACHINE_LEARNING_ENABLED` to true in your docker environment variables.
- On your Immich web app go to Administration > Settings > click on enable and set the url to your remote server ip:port

**Comment by traktuner** [comment]
Thank you very much!
IMMICH_MACHINE_LEARNING_ENABLED=true was missing ;)

**Comment by traktuner** [comment]
One last question - is there a way to include Typesense into that image, or externally? Or is it just not possible to have search functionality with the noml image at all?

**Comment by martabal** [comment]
No you can't add typesense in the image, alpine use musl and typesense is compiled with glibc. But you can add typesense externally using these environment variables :   https://documentation.immich.app/docs/install/environment-variables#typesense

**Comment by traktuner** [comment]
Thank you very much!
