### ISSUE TITLE
[BUG] Problem generating RAW thumbnails

### ISSUE THREAD

**Issue by traktuner** [imagegenius/docker-immich#208]
Hello @martabal ,
I am not sure if my problem is related to immich or the noml image.
Please see the issue here:
https://github.com/immich-app/immich/issues/5004 
Thank you

**Comment by martabal** [comment]
I confirm, this is a noml issue, I'm closing your issue upstream

**Comment by traktuner** [comment]
Thank you very much!

**Comment by martabal** [comment]
Thanks to @hydazz , noml has been rebased to ubuntu. The image is larger but is compatible with raw images

**Comment by hydazz** [comment]
+ typesense has been added, and can be disable with a variable if needed

**Comment by traktuner** [comment]
> * typesense has been added, and can be disable with a variable if needed

Thank you! TYPESENSE_HOST is set because its external already, so it should ignore the now included typesense app I guess.
