### ISSUE TITLE
App Login does not work on iOS reverseproxy

### ISSUE THREAD

**Issue by 7eptem** [imagegenius/docker-immich#209]
i set up a reverse proxy for immich  and i can access and log in using the domain name, 
but when i try to set up the app i receive this error `check server url , email and  password`

**Comment by martabal** [comment]
Isn't it related to v1.86 ?

**Comment by martabal** [comment]
You have to wait v1.86.0 to be released, the client and the server must have the same version as precised in the release notes https://github.com/immich-app/immich/releases/tag/v1.86.0

**Comment by 7eptem** [comment]
> You have to wait v1.86.0 to be released, the client and the server must have the same version as precised in the release notes https://github.com/immich-app/immich/releases/tag/v1.86.0

thanks for the info, i will come with a update when new iOS app is available
