### ISSUE TITLE
v1.86.0 Breaking Change: New Map System, Missing Assets

### ISSUE THREAD

**Issue by ghost** [imagegenius/docker-immich#212]
There's new assets that needs to be copied by the Dockerfile(s):

https://github.com/immich-app/immich/tree/main/server/assets

Someone else noticed this: https://github.com/immich-app/immich/issues/5031#issuecomment-1809954200

Until this happens, users using this image will be unable to view the map at all.

**Comment by martabal** [comment]
Thanks for the report, I will add it to #210
