### ISSUE TITLE
Immich v1.88.0 Announcement

### ISSUE THREAD

**Issue by Tyree** [imagegenius/docker-immich#219]
Given the v1.88 announcement and the breaking changes, will users of this template have to perform and special steps or will the needed steps in the announcement be included in the new template?

Thanks so much for making it easy for us CA users!

**Comment by martabal** [comment]
Nope, it won't affect you [as commented](https://github.com/immich-app/immich/discussions/5086#discussioncomment-7593274) in the announcement post

**Comment by Tyree** [comment]
My bad, @martabal , I did a search on that page for "unRAID" and missed that post. Sorry.

**Comment by guim31** [comment]
I just updated my Immich container on Unraid, and the app won't launch.

Here is what is in the logs : 

```
Node.js v20.9.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/app/immich/web/build/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by martabal** [comment]
The build is currently broken

**Comment by guim31** [comment]
Oh ok !

**Comment by hydazz** [comment]
> The build is currently broken

Is it?

**Comment by Tyree** [comment]
> The build is currently broken

It seems to be working for me, other than the seemingly unrelated log errors I mentioned in my new issue posted today.
