### ISSUE TITLE
Permissions could not be set. This is probably because your volume mounts are remote or read-only.

### ISSUE THREAD

**Issue by mattrowe84** [imagegenius/docker-immich#220]
I am not sure why this is occurring.  I am using the Unraid container from the community app (v1.88.0) and the import path/share has rwx for all user groups.  I am not sure what the problem is, it churns through the directory and all files have a read only cannot change permissions entry in the log.  Again all files, folders, and directories are 777.  So I am really not sure what the problem is

Update: I figured it out, I just used the "Reset Permission" tool and that fixed everything.

**Comment by mattrowe84** [comment]
[immich docker log.txt](https://github.com/imagegenius/docker-immich/files/13421891/immich.docker.log.txt)

**Comment by martabal** [comment]
You can ignore those logs. The official immich documentation recommends to use a read only mount to be sure Immich does not change your files. But with a read only mount this also means you have to make sure you set the right file permissions for every files in /import.

I'll open a PR to mute those logs

**Comment by martabal** [comment]
Yes I think it makes sense : If you trust Immich / don't want to use read only volumes, it's great just to change the file permissions for that folder. Somebody had trouble last week because of file permissions in that folder

**Comment by mattrowe84** [comment]
I figured it out, I just used the "Reset Permission" tool and that fixed everything
