### ISSUE TITLE
Getting a lot of errors - ECONNRESET and Not Ready or Lagging

### ISSUE THREAD

**Issue by Tyree** [imagegenius/docker-immich#221]
Last night I was working on adding names to the detected faces when suddenly the People page wouldn't reload. Then same for the Explore page. Checked the logs and it was slammed full of errors like:
`Request #1700568114431: Request to Node 0 failed due to "ECONNRESET socket hang up"`
and 
```
Request #1700568114431: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
Request #1700568114431: Sleeping for 4s and then retrying request...
```
and
`Request #1700568324697: Request to Node 0 failed due to "ERR_REQUEST_ABORTED error request aborted"`

After some googling, I tried stopping the container, deleting the typesense folder and restarting the container. That got the pages loading again, but the logs are still quickly filling with these errors.

That was prior to the 1.88 update. I went ahead and did that this morning, which was successful, but the errors in the logs continue.

**Comment by Tyree** [comment]
Also, this one popping up here and there during operations:
```
[Nest] 187  - 11/21/2023, 7:19:00 AM   ERROR [StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.onclose (node:internal/streams/end-of-stream:159:30)
    at ServerResponse.emit (node:events:526:35)
    at emitCloseNT (node:_http_server:1023:10)
    at Socket.onServerResponseClose (node:_http_server:278:5)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)
```

**Comment by hydazz** [comment]
@martabal might be wrong here,

`Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"` should only appear when you are starting the container, if the errors keep happening I could only assume that your hardware is underpowered, and `Not Ready or Lagging` is the answer here.

`ERROR [StreamableFile] Premature close`, is again, exactly what it says, premature closure, when you hover over a video, it plays, when you take your mouse off that video, it prematurly closes the stream. these can be safely ignored.

are you running immich on a potato (raspberry pi) or a dedicated server?

**Comment by Tyree** [comment]
> are you running immich on a potato (raspberry pi) or a dedicated server?
Definitely not a potato. i7 12700k, 64GB RAM, 
![specs](https://github.com/imagegenius/docker-immich/assets/5395363/056e14eb-e25f-4675-9ba7-761a074a953d)
I've never had any issue running it up until now. I did just add a large library of existing photos to it, but all jobs are completed.

**Comment by Tyree** [comment]
Immich CPU usage seems to be bouncing between 10% and 20% even at idle. Maybe it's working on something in the background whether there are jobs running or not?

**Comment by martabal** [comment]
> @martabal might be wrong here,

No you're correct

Indeed, you can safely ignore `ERROR [StreamableFile] Premature close` errors.
The typesense is synchronized with your db on startup. AFAIK, the only solution to your problem is : 
1. Stop your immich container
2. Remove the typesense folder in `/config`
3. Restart your immich container

**Comment by Tyree** [comment]
Just saw this error come up in the terminal log:
`[Nest] 1068  - 11/21/2023, 8:11:27 AM   ERROR [TypesenseRepository] Unable to index documents`

This is with me not doing anything. Could it still be working in the background on something?

I did the typesense folder delete last night. But I will try it again.

**Comment by Tyree** [comment]
@martabal 
So I went to delete the typesense folder again and it wasn't there. ????
Tried starting the container again and it's just filling with the Not Ready or Lagging and ECONNRESET/ECONNABORTED errors.
The typesense folder is not in the immich config folder.
Also new error:
```
[Nest] 2814  - 11/21/2023, 8:22:15 AM   ERROR [JobService] Unable to run job handler (search/search-index-faces): ServerError: Request failed with HTTP code 503 | Server said: Not Ready or Lagging
[Nest] 2814  - 11/21/2023, 8:22:15 AM   ERROR [JobService] ServerError: Request failed with HTTP code 503 | Server said: Not Ready or Lagging
    at ServerError.TypesenseError [as constructor] (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ServerError (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/ServerError.js:25:42)
    at ApiCall.customErrorForResponse (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:376:21)
    at /app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:225:58
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 2814  - 11/21/2023, 8:22:15 AM   ERROR [JobService] Object:
{}
```

**Comment by martabal** [comment]
Do you have the correct file permissions in `/config` ?

**Comment by Tyree** [comment]
I had to do this before about a month ago (different issue/error) and it created the typesense folder again, no problem. What should the permissions be. I will make sure.

**Comment by Tyree** [comment]
Ugh. Okay. So, I was using code-server to browse the folders and delete things. I went in through the unRAID interface instead and the typesense folder was there. I deleted it again and restarted the container. It created the typesense folder, but the errors came right back.
I mean, maybe I am dumping too much on it. It starts with a this line:
`[Nest] 1054  - 11/21/2023, 8:27:23 AM     LOG [SearchService] Indexing 72088 faces`
Then it immediately went into the lagging and conn reset errors again.

**Comment by martabal** [comment]
Uh, 72088 faces is huge, it might be the issue

**Comment by Tyree** [comment]
> Uh, 72088 faces is huge, it might be the issue

Do you think it'll settle down once it has processed them? I loaded the majority of my photo library into Immich yesterday via external library. Just more than it can handle. But I don't know if this is temporary until it works through it, or if it will always be this way with that many photos.

**Comment by Tyree** [comment]
@martabal Do you think I should ask the load question on the main Immich repo? Like is this a permanent wall or if it will eventually chew through it and settle down?

**Comment by martabal** [comment]
Let the time for the server to index your faces. If you still experience issues after an hour, you can open a new discussions on the Immich repo. FYI, there's an open PR to migrate from typesense to postgres.

**Comment by Tyree** [comment]
> Let the time for the server to index your faces. If you still experience issues after an hour, you can open a new discussions on the Immich repo. FYI, there's an open PR to migrate from typesense to postgres.

Okay. I'll leave it alone for a while and let it chew. Although I don't think an hour will be enough. It started this yesterday. So it had all night with no one using it to work on things.

I'm not familiar with typesense,I didn't know it was an option to postgres. So, when I delete the typesense folder, is it having to start over creating a database of sorts?

**Comment by muzhaqi16** [comment]
Same issue here, it started last night after updating.

```
Request #1700590469584: Sleeping for 4s and then retrying request...
Request #1700590469584: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
Request #1700590469584: Sleeping for 4s and then retrying request...
/app/immich/server/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23
        var _this = _super.call(this, message) || this;
                           ^

ServerError: Request failed with HTTP code 503 | Server said: Not Ready or Lagging
    at ServerError.TypesenseError [as constructor] (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ServerError (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/ServerError.js:25:42)
    at ApiCall.customErrorForResponse (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:376:21)
    at /app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:225:58
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatus: 503
}

Node.js v20.9.0
```

**Comment by muzhaqi16** [comment]
After deleting the `config/typesense` folder and restarting the server, it went back to normal after 45 minutes.

**Comment by Tyree** [comment]
Mine also settled down after a couple hours. Seems fine now.

**Comment by Tyree** [comment]
Updated to latest version just now and it started again. I assume it'll stop after a bit. Seems strange though.

**Comment by martabal** [comment]
Yes it's normal, typesense synchronizes the whole db on everything startup

**Comment by hydazz** [comment]
https://github.com/imagegenius/docker-immich/pull/248
