### ISSUE TITLE
1.88.X-noml contains no /app/immich/server/www folder

### ISSUE THREAD

**Issue by rgarcia6520** [imagegenius/docker-immich#222]
Upgrading today to `1.88.1-noml` & `1.88.2-noml` images the `/app/immich/server/www/` folder isn't created, but looks like it should be created and populated within the Dockerfile

Web UI shows: `ENOENT: no such file or directory, stat '/app/immich/server/www/index.html'`

```
root@b55ebdd5c3da:/# ls /app/immich/server/
assets  dist  node_modules  package.json  package-lock.json
```

**Comment by martabal** [comment]
Should be fixed with #223
