### ISSUE TITLE
Service doesn't seem to be running

### ISSUE THREAD

**Issue by fdw** [imagegenius/docker-immich#230]
After an update this week (to `sha256:69b6954ebb30b179298640595a7bab0fe50112067bb203e0d99dc9a826868093`), the main service doesn't seem to respond anymore. Calling it results in a `connection refused`.
The logs don't show anything interesting, unfortunately. I can see that `Immich Server is listening on http://[::1]:3001 [v1.88.2] [PRODUCTION]`, but there is no mention of other services running, especially not on `8080`.
There's also nothing suspicious in the mounted volumes. Apparently, the container is happy, just not answering my requests.

An update to the latest image hasn't improved anything, either.

I've reverted back to `:1.87.0`, and it works again. The log is a bit different, too:
After `Immich Server is listening on http://[::1]:3001 [v1.87.0] [PRODUCTION]` (same as before), there is more happening:
```
[ig-init] done.
Listening on 0.0.0.0:3000
Starting gunicorn 21.2.0                           
Listening at: http://0.0.0.0:3003 (445)            
Using worker: uvicorn.workers.UvicornWorker        
Booting worker with pid: 502                       
Starting Nest application...
[...]
Immich Microservices is listening on http://[::1]:3002 [v1.87.0] [PRODUCTION] 
```
I don't see this happening with the newer images.

**Comment by martabal** [comment]
Are you using the arm version ?

**Comment by fdw** [comment]
Yes, sorry: `arm64`

**Comment by fdw** [comment]
Gods, you're fast! Thank you!

**Comment by fdw** [comment]
And it works. Thank you 🙂
