### ISSUE TITLE
Jobs page does nothing - zero logs either

### ISSUE THREAD

**Issue by TomasValenta** [imagegenius/docker-immich#234]
Hello @martabal,

first thank you for maintaining this all in one image! Username11111111111111111111111 and me we experienced this issue after the last update:
![image](https://github.com/imagegenius/docker-immich/assets/4901251/fa15164a-2c03-4360-bf02-b775418e47ef)
- I click missing, the counter goes up by 1, but nothing happens and zero logs are produced
- p.s. no thumbnails are generated but assets do get uploaded internally
- Only older photos show thumbnails
- Happened after the update
- Using the all in one container
- No changes to the storage location, only changed the port as per requirements

I am writing the issue here due to the response from the Immich team:

> If you're using the AIO container then you'll have to ask the folks who make that for help, we don't really know much about it here

[Full Immich discord issue thread link](https://discord.com/channels/979116623879368755/1178265510446637076)

**Comment by martabal** [comment]
Can you make sure you run the latest version ? (Run `docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/imagegenius/immich:latest`, the output should be `ghcr.io/imagegenius/immich@sha256:ce334d16f96457e98cc62f60eac3b9390f66a3e8a290582fe5f21119466568ea`)

**Comment by TomasValenta** [comment]
I'll check, I dealt with it last night :)

**Comment by TomasValenta** [comment]
It seems to be working again after the last update, thanks a lot Martin!

**Comment by martabal** [comment]
> It seems to be working again after the last update, thanks a lot Martin!

Nice !
