### ISSUE TITLE
successful connection to Postgres15, but new errors with "permission denied for schema public..."

### ISSUE THREAD

**Issue by dkerlee** [imagegenius/docker-immich#245]
might be related to this [stackoverflow post](https://stackoverflow.com/questions/67276391/why-am-i-getting-a-permission-denied-error-for-schema-public-on-pgadmin-4)

I double checked server, database, user, and pass in the unraid docker template. The error started coming up.

![postgres errors](https://github.com/imagegenius/docker-immich/assets/6242339/92bf6988-4152-47d9-ba51-893914d17d47)

**Comment by martabal** [comment]
Indeed, this is related to postgres 15. Have you created an user for your immich database ?
