### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by ngosang** [imagegenius/docker-immich#251]
`DISABLE_IMMICH_MACHINE_LEARNING` should be `DISABLE_MACHINE_LEARNING`

**Comment by martabal** [comment]
Thanks, we were using `DISABLE_MACHINE_LEARNING` because a few months ago Immich didn't have a environment variable OOTB to disable machine learning. There is now `MACHINE_LEARNING_ENABLED`

Fixed with #248

**Comment by ngosang** [comment]
You are not fixing the issue in your PR.
![image](https://github.com/imagegenius/docker-immich/assets/10577978/2f19f296-da12-4b13-be93-d6e9ded8feaf)

**Comment by martabal** [comment]
Yes I am, the README is generated with `readme-vars.yml` by the bot

**Comment by dnlldl** [comment]
There are currently 11 mentions of TYPESENSE in the README.

**Comment by martabal** [comment]
> There are currently 11 mentions of TYPESENSE in the README.

Yes and ? `v1.91` will get rid of typesense but it's not released yet. So I think it makes sense to keep mentioning typesense in the README. Again, when it will be released and the PR will be merged, the bot will generate the README based on the content of the `readme-vars.yml` file which contains 3 mentions of typesense and all are in the changelog

**Comment by dnlldl** [comment]
> > There are currently 11 mentions of TYPESENSE in the README.
> 
> Yes and ? `v1.91` will get rid of typesense but it's not released yet. So I think it makes sense to keep mentioning typesense in the README. Again, when it will be released and the PR will be merged, the bot will generate the README based on the content of the `readme-vars.yml` file which contains 3 mentions of typesense and all are in the changelog

v1.91 is finally out, looking forward to test all of this in Unraid once I'm back home on Sunday. A new template is suggested to remove the var.
