### ISSUE TITLE
v1.91.2-alpine won't start

### ISSUE THREAD

**Issue by traktuner** [imagegenius/docker-immich#256]
Only one line in thel log, when the container gets created:

s6-rc-compile: fatal: during resolution of bundle user: undefined service name init-test-run
I am on an amd64 system.

Currently using the noml image which works 👍
Anything I can do on my end?
Thanks!

**Comment by hydazz** [comment]
minor oopsie on our end https://github.com/imagegenius/docker-immich/commit/25f2694126a165c1fd09d66425d59c620fd0cb1e

repull the image once that builds and it should work 🙂

**Comment by traktuner** [comment]
Thanks a lot :)

**Comment by traktuner** [comment]
hey @hydazz 
the error is still there unfortunately.

**Comment by traktuner** [comment]
oh, it's a new error:
s6-rc-compile: fatal: during dependency resolution for service init-config-end: undefined service name init-test-run

**Comment by hydazz** [comment]
seems i missed another pesky file https://github.com/imagegenius/docker-immich/commit/4acd3abc073296f3e5e8b20395a72cc8efd80d16 should fix that one

**Comment by traktuner** [comment]
That was it, works now - thanks again :)
