### ISSUE TITLE
s6-rc-compile: fatal: during dependency resolution for service init-config-end: undefined service name init-test-run

### ISSUE THREAD

**Issue by HeresJonny** [imagegenius/docker-immich#257]
The bug
Immich doesn't start with the above message since the latest update I got just now.

The OS that Immich Server is running on
Unraid 6.12.6

Version of Immich Server
alpine 2.0.4

Reproduction steps
1. Happens all the time when I check the log
2. rollback to previous backup doesn't fix the issue

**Comment by HeresJonny** [comment]
Ah, I see now the error reported previously by another user is the same. Will wait for new build then.

**Comment by hydazz** [comment]
The new build is pushed, try updating?
