### ISSUE TITLE
Duplicate photos and videos after upgrading to 1.91.2

### ISSUE THREAD

**Issue by gottoesplosivo** [imagegenius/docker-immich#258]
Hello,

I run immich on UNRAID 6.12.4.

After upgrading to 1.91.2 and changing the potsgres repo to tensorchord/pgvecto-rs:pg15-v0.1.11 I suddenly have a bunch of duplicate pics and videos.

How can I troubleshoot this?

**Comment by martabal** [comment]
Hello, this is probably an upstream issue. 

I don't think changing the postgres repo have anything to do with duplicates, however if your issues is about live photos, Immich [v1.91.0 release notes](https://github.com/immich-app/immich/releases/tag/v1.91.0) provide instructions for this case. If this is not about live photos, please open an issue in (the upstream repo](https://github.com/immich-app/immich)
