### ISSUE TITLE
immich-admin command not working 

### ISSUE THREAD

**Issue by Janczykkkko** [imagegenius/docker-immich#260]
Hey guys, i'm on 1.91.3 and the command immich-admin (in any form) in the immich container is throwing errors:

`root@ead93a9cbbac:/# immich-admin enable-password-login`

`Invalid app name: admin-cli. Expected one of immich|microservices|cli` 

I'm fairly sure this worked before. Logs don't show anything related to this.

**Comment by martabal** [comment]
Should be fixed with #261. Thanks for the report

**Comment by Janczykkkko** [comment]
thanks for quick response! cheers
