### ISSUE TITLE
Problem deleting files from imported folder

### ISSUE THREAD

**Issue by gedas07** [imagegenius/docker-immich#276]
Problem deleting files from imported folder

Well that's it, I delete image files from folders and they continue to be seen in the gallery
Isn't it possible that when I delete a photo from the imported folder, it can no longer be seen in the gallery?

Thank you so much

![image](https://github.com/imagegenius/docker-immich/assets/42668878/1b936a18-3a8f-4b09-bb97-4dc5247373db)

**Comment by martabal** [comment]
This is the correct behavior. For now, external libraries must be managed by the user, which includes deleting and changing asset metadata.
