### ISSUE TITLE
Images are not deselected

### ISSUE THREAD

**Issue by elBelgg** [imagegenius/docker-immich#287]
I just updated Immich to version 1.93.2 and I have tried deleting some images. I have noticed that if you select the image and delete it, the image is not deselected (it remains selected even after being deleted).

**Comment by martabal** [comment]
I don't think this is related to this AIO image in particular

Please re-open your issue in the upstream repo https://github.com/immich-app/immich

**Comment by elBelgg** [comment]
True, sry
