### ISSUE TITLE
why there is no "Categories" in the Explore page?

### ISSUE THREAD

**Issue by Shihta** [imagegenius/docker-immich#298]
Hi,

I'm using the version `arm64v8-1.94.1-alpine`. there is no "Categories" in the Explore page, the screenshot is as the follows:

![截圖 2024-02-18 下午3 39 58](https://github.com/imagegenius/docker-immich/assets/5186176/3ee9e7d5-40ee-4eb9-a38c-3c82bee53118)

does that require `noml` version to enable?

what I need is to list all videos only, is there any way to do that without Categories function?

Thanks!

**Comment by martabal** [comment]
Hello !

No, that feature existed a few months ago and relied on machine learning. But it was removed because it was too imprecise.

**Comment by Shihta** [comment]
> Hello !
> 
> No, that feature existed a few months ago and relied on machine learning. But it was removed because it was too imprecise.

thanks for the information!
