### ISSUE TITLE
Latest version fails to install

### ISSUE THREAD

**Issue by Phantomx2** [imagegenius/docker-immich#303]
Trying to update an existing Immich docker or install from scratch, getting this error:

```
docker run
  -d
  --name='immich'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='192.168.0.200'
  -e 'DB_USERNAME'='yverde'
  -e 'DB_PASSWORD'='Psychique1'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.0.200'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'=''
  -e 'MACHINE_LEARNING_GPU_ACCELERATION'=''
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8080:8080/tcp'
  -v '/mnt/user/Media/Immich/':'/photos':'rw'
  -v '':'/import':'ro'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich'
docker: invalid spec: :/import:ro: empty section between colons.
See 'docker run --help'.

The command failed.
```

**Comment by newillusions** [comment]
Mine didn't throw an error during the upgrade, but it's not working and I'm getting the following errors repeating:
`
        Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.
    
        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23
    
    Node.js v20.11.1
    [Nest] 9363  - 02/21/2024, 7:55:43 AM     LOG [CommunicationRepository] Initialized websocket server
    /app/immich/server/dist/domain/database/database.service.js:137
            throw new Error(`
                  ^
`

**Comment by kflinderman** [comment]
Installing [Docker Patch](https://forums.unraid.net/topic/154107-plugin-docker-patch-6128/) fixed the install for me, but I've now lost my settings connecting to postgress, but hope this helps you

**Comment by Phantomx2** [comment]
Docker patch fixed the installation, but now I'm having the same issue as @newillusions

**Comment by Phantomx2** [comment]
I was able to "fix" it by changing the postgreSQL repo to `tensorchord/pgvecto-rs:pg15-v0.2.0`
However I was getting a lot of errors in the log about upgrading, so I shut down all of the related dockers and restarted them and it worked after that.

**Comment by newillusions** [comment]
> I was able to "fix" it by changing the postgreSQL repo to `tensorchord/pgvecto-rs:pg15-v0.2.0` However I was getting a lot of errors in the log about upgrading, so I shut down all of the related dockers and restarted them and it worked after that.

This worked for me too.
Just for the record, I'm still on 12.6 as 12.8 was causing me issues. So can't install / don't need the Docker Patch.
