### ISSUE TITLE
I broke Immich on Unraid

### ISSUE THREAD

**Issue by fethomm** [imagegenius/docker-immich#304]
I did not read about the braking  changes in v1.95.0 and now Immich will not work. The logs point to pgvecto.rs 2.0 missing as the reason. Is there an easy way for a docker newb to fix this?

**Comment by martabal** [comment]
Hello, everything is explained in Immich release notes https://github.com/immich-app/immich/releases/tag/v1.95.0

**Comment by fethomm** [comment]
Yes, I read that before opening this issue. Unfortunately it only covers docker-compose, as far as I can see. My setup is with Unraid.

**Comment by fethomm** [comment]
I just tried to install with the latest docker-compose.yaml, which already has pg14-v0.2.0. After compose up, I get  line 14: mapping key "services" already defined at line 1

**Comment by martabal** [comment]
Updating a docker image is not a docker-compose feature https://github.com/imagegenius/docker-immich/issues/254#issuecomment-1935803120

**Comment by fethomm** [comment]
I am not trying to update, this is a new stack.

**Comment by martabal** [comment]
I don't understand. Are you using the CA template, the AIO docker-compose.yml or the official docker-compose.yml ?

**Comment by martabal** [comment]
Then, it's not the correct repo, please see the tickets opened in the upstream repo

**Comment by martabal** [comment]
No problem, It can be a bit hard to understand.

To correctly work, immich requires multiple services (server, microservices, machine-learning, postgres, redis). This repo hosts a custom docker image which bundles the server, microservices and machine-learning services.

So, when running the official docker-compose, you're running 5 containers and with this custom image you're running "only" 3 containers. It has other advantages such as the ability of running custom scripts and more.

So on unraid, to make immich work, the official way is to use the docker-compose plugin and use the docker-compose.yml. With this image, you can use only the CA templates (no need to use the docker-compose plugin)
