### ISSUE TITLE
Unraid The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

### ISSUE THREAD

**Issue by madmax5900** [imagegenius/docker-immich#305]
Hello!

I just updated Docker on my Unraid server.

Unfortunately I now get the following error.

The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

I have already read that with the new version you need the 0.2.0 version of pgvecto.rs.

How to change this on Unraid?

**Comment by martabal** [comment]
Hello, you need to update your Postgres image. For more details, please read Immich release notes https://github.com/immich-app/immich/releases/tag/v1.95.1

**Comment by madmax5900** [comment]
Hello!

Thank you for your answer.

But where can I find the docker-compose.yml file under Unraid?

**Comment by martabal** [comment]
Unraid does not use docker-compose, you just need to update the docker image https://github.com/imagegenius/docker-immich/issues/254#issuecomment-1935803120

**Comment by madmax5900** [comment]
Thanks for the help, everything is working again now.

**Comment by martabal** [comment]
Great news, sorry if I confused you.

Enjoy Immich !
