### ISSUE TITLE
Error:          The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

### ISSUE THREAD

**Issue by calm108** [imagegenius/docker-immich#306]
I updated Immich on Unraid per the docker update as I have done every time there was an update but now I am getting this error. 

Im not sure how to correct the issue.  I followed the link on how to query the DB but that doesn't really help .....

**Comment by martabal** [comment]
Did you update the Postgres image ?

**Comment by calm108** [comment]
Yeah totally missed that.   Followed steps here and all good now:

https://newreleases.io/project/github/immich-app/immich/release/v1.95.0

**Comment by calm108** [comment]
Closing.
