### ISSUE TITLE
CLI ERROR  unable to run the CLI 

### ISSUE THREAD

**Issue by ragaimeena** [imagegenius/docker-immich#307]
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/app/cli/dist/src/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1

when I try to use CLI it seems that there is a missing package

**Comment by martabal** [comment]
Thanks for the report

**Comment by bigsam223** [comment]
yes,me too. how can i fix this guys?

**Comment by bigsam223** [comment]
> yes,me too. how can i fix this guys?

before version:1.94-1
update to 1.95-1
i try to update  gvecto-rs:pg14-v0.1.11 to pgvecto-rs:pg14-v0.2.0


immich      | Node.js v20.11.1
immich      | [Nest] 362  - 02/22/2024, 7:25:52 PM     LOG [CommunicationRepository] Initialized websocket server
postgres14  | 2024-02-22 11:25:52.218 UTC [316] ERROR:  pgvecto.rs: The extension is upgraded so all index files are outdated.
postgres14  | 	ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
postgres14  | 2024-02-22 11:25:52.218 UTC [316] STATEMENT:  
postgres14  | 	          SELECT idx_status
postgres14  | 	          FROM pg_vector_index_stat
postgres14  | 	          WHERE indexname = $1
immich      | [Nest] 362  - 02/22/2024, 7:25:52 PM    WARN [DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
immich      | /app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
immich      |             throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
immich      |                   ^
immich      | 
immich      | QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.
immich      | ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich      |     at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich      |     at async DataSource.query (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:350:20)
immich      |     at async DatabaseRepository.shouldReindex (/app/immich/server/dist/infra/repositories/database.repository.js:127:25)
immich      |     at async /app/immich/server/dist/domain/database/database.service.js:41:21
immich      |     at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
immich      |   query: '\n' +
immich      |     '          SELECT idx_status\n' +
immich      |     '          FROM pg_vector_index_stat\n' +
immich      |     '          WHERE indexname = $1',
immich      |   parameters: [ 'clip_index' ],
immich      |   driverError: error: pgvecto.rs: The extension is upgraded so all index files are outdated.
immich      |   ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich      |       at /app/immich/server/node_modules/pg/lib/client.js:526:17
immich      |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich      |       at async PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich      |       at async DataSource.query (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:350:20)
immich      |       at async DatabaseRepository.shouldReindex (/app/immich/server/dist/infra/repositories/database.repository.js:127:25)
immich      |       at async /app/immich/server/dist/domain/database/database.service.js:41:21
immich      |       at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
immich      |     length: 203,
immich      |     severity: 'ERROR',
immich      |     code: 'XX000',
immich      |     detail: undefined,
immich      |     hint: undefined,
immich      |     position: undefined,
immich      |     internalPosition: undefined,
immich      |     internalQuery: undefined,
immich      |     where: undefined,
immich      |     schema: undefined,
immich      |     table: undefined,
immich      |     column: undefined,
immich      |     dataType: undefined,
immich      |     constraint: undefined,
immich      |     file: 'error.rs',
immich      |     line: '7',
immich      |     routine: undefined
immich      |   },
immich      |   length: 203,
immich      |   severity: 'ERROR',
immich      |   code: 'XX000',
immich      |   detail: undefined,
immich      |   hint: undefined,
immich      |   position: undefined,
immich      |   internalPosition: undefined,
immich      |   internalQuery: undefined,
immich      |   where: undefined,
immich      |   schema: undefined,
immich      |   table: undefined,
immich      |   column: undefined,
immich      |   dataType: undefined,
immich      |   constraint: undefined,
immich      |   file: 'error.rs',
immich      |   line: '7',
immich      |   routine: undefined
immich      | }
immich      | 
immich      | Node.js v20.11.1

**Comment by martabal** [comment]
There's an error in the script, I'll fix it later today

**Comment by bigsam223** [comment]
no, you don't ,i fix it.
guys, i use this fix.
start
1.ssh to you immich sever.
2. Adjust compose to hold the new image versions
3. docker compose down && docker compose pull
4. docker compose up
5. PSQL throws errors
6. docker compose down
7. docker compose up -d immich-database
8. docker exec -it immich-database bash
9. Inside container connect to database via `psql -U postgres -d immich-psgdb(yours db name,if dont know "psql -U postgres -l"
)` and run the commands from the release instructions to manually upgrade pgvecto-rs from 0.1.11 to 0.2.0.
and use this:
"
BEGIN;
UPDATE pg_catalog.pg_extension SET extversion = '0.2.0' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';
ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';
SELECT pgvectors_upgrade();
COMMIT;
"
11. Perceive error when executing `SELECT pgvectors_upgrade();`
https://github.com/immich-app/immich/issues/7327

**Comment by martabal** [comment]
That's a different issue ...

**Comment by ragaimeena** [comment]
I agree, different issue.
martabal thank you for taking the time to look into this.
I am on unraid, I hope you will be able to fix it.
Do I need to uninstall and reinstall the CLI later from the console?
Thank you

**Comment by martabal** [comment]
No worries, it's a really small change, it won't be hard to fix, but I don't have my PC until this evening ahah.

Until then, you can use the docker version of the CLI or execute `node /app/cli/dist/index.js upload [...]` instead of `immich upload [...]` inside the Immich container.

**Comment by martabal** [comment]
Hey, it should be fixed
