### ISSUE TITLE
Docker disapeared and can't reinstall help?

### ISSUE THREAD

**Issue by TheRealSubwars** [imagegenius/docker-immich#315]
Hi, can someone please help me, I just tried to get onto immich and wasn't able to, checked and the docker was gone. tried to reinstall and its coming up failed, tried putting an _old on the end of the immich folder so it would recreate a new one, tried installed the new postgress_immich that i saw available. All i get is the below. On Unraid, usging community plugins to install.

 -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='192.168.1.100'
  -e 'DB_USERNAME'='postgres'
  -e 'DB_PASSWORD'='postgres'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.1.100'
  -e 'DB_PORT'='5433'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'=''
  -e 'MACHINE_LEARNING_GPU_ACCELERATION'=''
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '18181:8080/tcp'
  -v '/mnt/user/Photos/Immich/':'/photos':'rw'
  -v '':'/import':'ro'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich'
docker: invalid spec: :/import:ro: empty section between colons.
See 'docker run --help'.

The command failed.

**Comment by martabal** [comment]
You can't have an empty string for /import. Remove that volume or set a value to it
