### ISSUE TITLE
About thumbnails for external images

### ISSUE THREAD

**Issue by PDSCi996** [imagegenius/docker-immich#317]
I deployed immich on my nas, and set up an external image library and imported it successfully, but I found a thumbnail problem. 1-2 thumbnails were automatically generated for each photo, and they appeared in the gallery and people. However, photos uploaded through mobile phones do not have this problem. I am not sure about the cause and solution of this problem. I hope an expert can give me some advice. I would be very grateful.

**Comment by martabal** [comment]
Not sure to understand what's your issue. Immich generates at least 2 thumbnails for every assets: one small thumbnail (for the timeline) and one large thumbnail (for the asset viewer). It does the same thing for external libraries or the standard library
If you have any questions about Immich itself, it's better to ask them on the upstream repo.

**Comment by PDSCi996** [comment]
> Not sure to understand what's your issue. Immich generates at least 2 thumbnails for every assets: one small thumbnail (for the timeline) and one large thumbnail (for the asset viewer). It does the same thing for external libraries or the standard library If you have any questions about Immich itself, it's better to ask them on the upstream repo.

Maybe I didn't express it clearly. What I mean is that for external images, the thumbnails generated by immich will appear in the timeline together with the original images themselves. The result is that when you look at the timeline, there will be at least two and at most four or five at the same time. Exactly the same photos appear, and you can't tell which one is the original picture. You can only tell the difference when you open them one by one, but you can't hide or delete these thumbnails.

**Comment by martabal** [comment]
Sounds related to https://github.com/immich-app/immich/issues/7843

I'm closing it because I don't this it's not an issue with this AIO image.
