### ISSUE TITLE
Can't get to the Immich GUI

### ISSUE THREAD

**Issue by LuRaBu** [imagegenius/docker-immich#318]
Whenever
 I try to access the Immich GUI I get a screen error message saying the site can't be reached. I've checked both internet and proxy everything seems ok. What else should I try?

**Comment by martabal** [comment]
Can you share your docker logs ?

**Comment by LuRaBu** [comment]
Hi, thanks for the reply. 
I'm new to this "server" business. I can generate the log from the Immich container, but I'm struggling to copy/paste in order to forward it to you. As soon as I figure this one out, I'll forward it to you.
Thanks,Luis

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Mar 15, 2024 at 1:29 PM, ***@***.***> wrote:   


Can you share your docker logs ?

**Comment by LuRaBu** [comment]
Ok. I had to stop Immich in order to be able to copy the logs. Sorry for the mess. I'm attaching the log.
Thanks for your help.
    On Friday, March 15, 2024 at 01:29:12 PM EDT, martin ***@***.***> wrote:  
 
 


Can you share your docker logs ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
text  error  warn  system  array  login  

  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'extension.c',
  line: '535',
  routine: 'parse_extension_control_file'
}

Node.js v20.11.1
/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
                  ^

QueryFailedError: could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataSource.query (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:350:20)
    at async DatabaseRepository.createExtension (/app/immich/server/dist/infra/repositories/database.repository.js:63:9)
    at async DatabaseService.createVectorExtension (/app/immich/server/dist/domain/database/database.service.js:65:13)
    at async /app/immich/server/dist/domain/database/database.service.js:37:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
  query: 'CREATE EXTENSION IF NOT EXISTS vectors',
  parameters: undefined,
  driverError: error: could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
      at /app/immich/server/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async DataSource.query (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:350:20)
      at async DatabaseRepository.createExtension (/app/immich/server/dist/infra/repositories/database.repository.js:63:9)
      at async DatabaseService.createVectorExtension (/app/immich/server/dist/domain/database/database.service.js:65:13)
      at async /app/immich/server/dist/domain/database/database.service.js:37:13
      at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
    length: 193,
    severity: 'ERROR',
    code: '58P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'extension.c',
    line: '535',
    routine: 'parse_extension_control_file'
  },
  length: 193,
  severity: 'ERROR',
  code: '58P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'extension.c',
  line: '535',
  routine: 'parse_extension_control_file'
}

Node.js v20.11.1
[Nest] 6253  - 03/15/2024, 2:45:45 PM     LOG [CommunicationRepository] Initialized websocket server
[Nest] 6253  - 03/15/2024, 2:45:45 PM   FATAL [DatabaseService] 
        Failed to activate pgvecto.rs extension.
        Please ensure the Postgres instance has pgvecto.rs installed.

        If the Postgres instance already has pgvecto.rs installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'CREATE EXTENSION IF NOT EXISTS vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Alternatively, if your Postgres instance has pgvector, you may use this instead by setting the environment variable 'DB_VECTOR_EXTENSION=pgvector'.
        Note that switching between the two extensions after a successful startup is not supported.
        The exception is if your version of Immich prior to upgrading was 1.90.2 or earlier.
        In this case, you may set either extension now, but you will not be able to switch to the other extension following a successful startup.
      

** Press ANY KEY to close this window **

**Comment by martabal** [comment]
You don't use the correct postgres image, you have to use postgres with an extension called [pgvecto.rs ](https://github.com/tensorchord/pgvecto.rs). Here's the migration guide https://github.com/imagegenius/docker-immich/issues/254

**Comment by LuRaBu** [comment]
Martin,
I followed the instructions from the migration guide, but still face the same issue, not being able to connect to the GUI. I generated a new log and it suggests this is due to the version of  pgvecto.rs used.I do not understand the instructions they give to get over this issue.

Thanks again for your help,Luis
    On Friday, March 15, 2024 at 02:56:37 PM EDT, martin ***@***.***> wrote:  
 
 


You don't use the correct postgres image, you have to use postgres with an extension called pgvecto.rs . Here's the migration guide #254

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
text  error  warn  system  array  login  

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23

Node.js v20.11.1
/app/immich/server/dist/domain/database/database.service.js:140
            throw new Error(`
                  ^

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23

Node.js v20.11.1
/app/immich/server/dist/domain/database/database.service.js:140
            throw new Error(`
                  ^

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23

Node.js v20.11.1
/app/immich/server/dist/domain/database/database.service.js:140
            throw new Error(`
                  ^

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23

Node.js v20.11.1
/app/immich/server/dist/domain/database/database.service.js:140
            throw new Error(`
                  ^

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23

Node.js v20.11.1
[Nest] 650  - 03/15/2024, 3:12:44 PM     LOG [CommunicationRepository] Initialized websocket server
[Nest] 672  - 03/15/2024, 3:12:46 PM     LOG [CommunicationRepository] Initialized websocket server
[Nest] 694  - 03/15/2024, 3:12:48 PM     LOG [CommunicationRepository] Initialized websocket server
[Nest] 716  - 03/15/2024, 3:12:51 PM     LOG [CommunicationRepository] Initialized websocket server

** Press ANY KEY to close this window **

**Comment by martabal** [comment]
Oh my bad, yes you need to change the extension version.

I forgot to update it, I only have mentioned it in a comment https://github.com/imagegenius/docker-immich/issues/254#issuecomment-1935803120.

**Comment by LuRaBu** [comment]
Well, changed it to v0.2.0 and the issue persists. I even turned off the Windows firewall and the GUI still claims it can't connect. I've included the latest log.
    On Friday, March 15, 2024 at 03:35:08 PM EDT, martin ***@***.***> wrote:  
 
 


Oh my bad, yes you need to change the extension version.

I forgot to update it, I only have mentioned it in a comment #254 (comment).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
text  error  warn  system  array  login  

  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'error.rs',
  line: '7',
  routine: undefined
}

Node.js v20.11.1
/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
                  ^

QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.
ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCLIPEmbeddingIndex1700713994428.up (/app/immich/server/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/app/immich/server/dist/infra/repositories/database.repository.js:177:9)
    at async /app/immich/server/dist/domain/database/database.service.js:52:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
  query: '\n' +
    '      CREATE INDEX IF NOT EXISTS clip_index ON smart_search\n' +
    '      USING hnsw (embedding vector_cosine_ops)\n' +
    '      WITH (ef_construction = 300, m = 16)',
  parameters: undefined,
  driverError: error: pgvecto.rs: The extension is upgraded so all index files are outdated.
  ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
      at /app/immich/server/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddCLIPEmbeddingIndex1700713994428.up (/app/immich/server/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
      at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/app/immich/server/dist/infra/repositories/database.repository.js:177:9)
      at async /app/immich/server/dist/domain/database/database.service.js:52:13
      at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23 {
    length: 203,
    severity: 'ERROR',
    code: 'XX000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'error.rs',
    line: '7',
    routine: undefined
  },
  length: 203,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'error.rs',
  line: '7',
  routine: undefined
}

Node.js v20.11.1
[Nest] 22628  - 03/15/2024, 4:08:56 PM     LOG [CommunicationRepository] Initialized websocket server
Migration "AddCLIPEmbeddingIndex1700713994428" failed, error: pgvecto.rs: The extension is upgraded so all index files are outdated.
ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.

** Press ANY KEY to close this window **

**Comment by martabal** [comment]
That's an upstream issue, please see [this thread](https://github.com/immich-app/immich/issues/7327)

**Comment by LuRaBu** [comment]
Thank you Martin. Based on the last link you sent, I tried turning postgresql14 off and then back on before trying to access the WebUI, and this time it worked!!!
Thanks for your help and patience.
    On Friday, March 15, 2024 at 04:22:45 PM EDT, martin ***@***.***> wrote:  
 
 


That's an upstream issue, please see this thread

**Comment by martabal** [comment]
Nice !
