### ISSUE TITLE
Immich MAP feature

### ISSUE THREAD

**Issue by LuRaBu** [imagegenius/docker-immich#320]
Hi, I've got the Immich app working. The one thing I noticed is that the photos are not being associated with any map locations. I don't know if this is due to an incorrect setting or a supporting device not being in place. What is needed to have the map feature work?

**Comment by martabal** [comment]
You must have the latitude and longitude in the exif of your assets.

For any other questions, please ask in the upstream repositoryhttps://github.com/immich-app/immich/
