### ISSUE TITLE
Unraid - Machine learning not working 

### ISSUE THREAD

**Issue by Tmatz27** [imagegenius/docker-immich#321]
I'm not able to get machine learning or facial recognition working in unraid. I've got a tons of pictures with people in them and no matter how many times I run the facial recognition it always comes back empty. It completes the job in seconds even though it's going through thousands of photos. Not sure what to do, I can't find a log file or config file in the immich app data folder either so I can't post logs

**Comment by martabal** [comment]
Can you post the docker logs ? `docker logs Immich`

**Comment by Tmatz27** [comment]
I have included log files before i reran facial detection. After I ran facial detection again i recieved so many errors I could not see the whole log file in the console. The main statement is captured in a screen shot attached to this comment as well. The error just keeps repeating with different "id"s.  There is no config file in the folder so not sure how correct these errors. 
[Screenshot 2024-03-22 105809](https://github.com/imagegenius/docker-immich/assets/116435680/2bca2d7a-e8ea-4e0e-95c8-a20945d2701a)
[root@Tower~# docker logs immich.txt](https://github.com/imagegenius/docker-immich/files/14726025/root%40Tower.docker.logs.immich.txt)

**Comment by martabal** [comment]
Why is your machine url set to `127.0.0.0:443` ?
Have you changed something in the admin settings / template ?

**Comment by Tmatz27** [comment]
Nope, the rest of the docker is working correctly. Ill attach my setup. If there was a config file i think i would be able to fix this. 
![Screenshot 2024-03-21 160029](https://github.com/imagegenius/docker-immich/assets/116435680/72166b86-a5b2-4ae7-8f21-5b613c94778a)
![Screenshot 2024-03-21 160046](https://github.com/imagegenius/docker-immich/assets/116435680/979d73a6-be08-4e50-b4e4-24f034141bb0)

**Comment by martabal** [comment]
What's the machine learning URL in administration > settings > Machine Learning settings ?

**Comment by Tmatz27** [comment]
Wow i cant believe i missed that! it was set to 127.0.0.0. Im assuming i need to set this to my unraid server of 192.168.1.132 correct? It only has an intel igpu though. I have two other PCs with nvidia gpus so i could set it to those ip addresses?

**Comment by martabal** [comment]
No just hit `reset to default` and `save`.

Immich does not support multiple machine learning instances OOTB, but you can have it working by setting multiple immich_machine_learning containers and a load balancer. Really not straightforward but achievable.

**Comment by Tmatz27** [comment]
Not sure how that setting got changed but can confirm that facial recognition is currently working. Thank you for the help!

**Comment by Tmatz27** [comment]
I do have one follow up question. Im looking at the ML docs on the Immich page. It references inline adding the hardware acceleration config into the docker-compose.yml file but this is not present in the Unraid immich file system. Ive gone through every single folder and i can not find it

**Comment by martabal** [comment]
Yeah that's how you're supposed to deploy Immich with the "official" way to deploy Immich (with docker-compose). 

All information related to the deployment of this AIO image, including machine learning acceleration, can be found in the README of this repo.
