### ISSUE TITLE
Redis External - " no auth spam messages "

### ISSUE THREAD

**Issue by masterwishx** [imagegenius/docker-immich#326]
Using redis with no auth already in Unraid : 

Also removed REDIS PASSWORD ...

![image](https://github.com/imagegenius/docker-immich/assets/28630321/6020ef4c-0ded-484a-ad2d-7501394b621e)

**Comment by martabal** [comment]
I don't know how you deployed redis, but you probably have set a password

**Comment by masterwishx** [comment]
> I don't know how you deployed redis, but you probably have set a password

im very sorry , you are right , its my bad
