### ISSUE TITLE
ImportError: 'unexpected reloc type' On container start. (cuda)

### ISSUE THREAD

**Issue by Upmacc** [imagegenius/docker-immich#340]
### Bug Info
Upgraded my Unraid Immich container earlier today and noticed heavy error logging right after the container started.
Prior to the container update the machine learning functionality using cuda was working fine.

Extremely verbose error logs:
```
04/15/2024 02:07:09 PM [04/15/24 14:07:09] INFO     Booting worker with pid: 1097                   
04/15/2024 02:07:10 PM [04/15/24 14:07:10] ERROR    Exception in worker process           
.......             
04/15/2024 02:07:10 PM                              ImportError:                                       
04/15/2024 02:07:10 PM                              /config/machine-learning/cuda/.venv/lib/python3.11/
04/15/2024 02:07:10 PM                              site-packages/cv2/../opencv_python_headless.libs/li
04/15/2024 02:07:10 PM                              bopenblas-r0-f650aae0.3.3.so: unexpected reloc type
04/15/2024 02:07:10 PM                              0x10000001                                         
04/15/2024 02:07:10 PM [04/15/24 14:07:10] INFO     Worker exiting (pid: 1097)                         
04/15/2024 02:07:10 PM [04/15/24 14:07:10] ERROR    Worker (pid:1097) exited with code 3               
04/15/2024 02:07:10 PM [04/15/24 14:07:10] ERROR    Shutting down: Master                              
04/15/2024 02:07:10 PM [04/15/24 14:07:10] ERROR    Reason: Worker failed to boot.
```
See attached for full container startup log:
[immich logs 15_04_2023.log](https://github.com/imagegenius/docker-immich/files/14973469/immich.logs.15_04_2023.log)

### Following container parameter and vars are set:
Extra Parameters: `--runtime=nvidia`
MACHINE_LEARNING_GPU_ACCELERATION: `cuda`
MACHINE_LEARNING_WORKERS: `1`
MACHINE_LEARNING_WORKER_TIMEOUT: `120`
NVIDIA (NVIDIA_VISIBLE_DEVICES): `GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` (redacted)
NVIDIA_DRIVER_CAPABILITIES: `all`

### Version info
OS docker Immich is running on: Unraid v6.12.9
Latest version Nvidia Driver plugin: 2024.01.19 - Nvidia Driver Version: 550.67
Version of Docker Immich: Latest - v1.101.0-ig270
GPU: GTX 1060 6gb

Note: If I remove cuda from within the variables then this error will not appear, I have left this removed for now to stop the error logging.

I noticed a prior issue which appears to be in a similar area, for reference: [https://github.com/imagegenius/docker-immich/issues/337](https://github.com/imagegenius/docker-immich/issues/337)

**Comment by hydazz** [comment]
try delete `/config/machine-learning/`, then **recreate**/**force update** the container

**Comment by Upmacc** [comment]
Sweet that resolved my above error, thanks for the help and quick reply.  
I will keep an eye on it over the next week or so and see how it goes.

For anyone's having this specific issue in the future: Shell into the container and run the following recursive delete.
`rm -r /config/machine-learning/`
To force update the container, you can make a change in the Immich container template- in my case I re-enabled 'cuda'.  
This is a quick way to force the container to rebuild.
