### ISSUE TITLE
[QA] Import Folder has auto upload by container? 

### ISSUE THREAD

**Issue by masterwishx** [imagegenius/docker-immich#345]
Question :
Is container have auto check /Import container folder for auto upload?
Or we need manually create User script in Unraid for upload by immich CLI from this folder like in PhotoPrism?

**Comment by martabal** [comment]
the `/import` folder is the recommended folder to import your files when using the "external libraries" feature. The `/photos` folder is where your uploaded assets are stored and where Immich store thumbnails. There's a clear distinction between external libraries (mounted to `/import` and optional) and the upload library (mounted to `/photos` and required even if you only use external libraries). 

In your case you have 2 options:
- create a script to automatically upload your assets to the upload library
- use external library which scan new assets periodically and have an experimental feature to automatically detect new assets.

The principal distinction between the upload library and external libraries is that Immich won't touch / add files in external libraries, so it's not possible to edit / delete assets stored there.

**Comment by masterwishx** [comment]
Thanks for explaining 
Now I got it
It was a little confusing...

I made a script in Unraid for upload files from /Import to /photo library like was in PhotoPrism.

So I need mount external libraries under /Import/... 
And make another import folder for script to upload to library...

**Comment by masterwishx** [comment]
For now i made /pictures for external library (Photoprism)  , and /import for script to upload to Library /photo

**Comment by DastardlyDino** [comment]
after adding the "/import/" folder as an external database and scanning the folder will my photos and videos be automatically moved into the correct users /photo library?

**Comment by masterwishx** [comment]
> after adding the "/import/" folder as an external database and scanning the folder will my photos and videos be automatically moved into the correct users "/photo" library?

No, do you want add external storage or upload photos to user library?

**Comment by DastardlyDino** [comment]
> > after adding the "/import/" folder as an external database and scanning the folder will my photos and videos be automatically moved into the correct users "/photo" library?
> 
> No, do you want add external storage or upload photos to user library?

Upload a large amount of photos to a users library?
