### ISSUE TITLE
understanding library & upload folder

### ISSUE THREAD

**Issue by mich2k** [imagegenius/docker-immich#346]
Hello,
I know this might be overkill for an issue
I had issues with my docker vDisk growing and i noticed I did not map the volume of the uploads folder, not because I did not want to but because I did not know this folder existed at all

Now I am wondering, how does this folder differ from library? In official docs I cant find anywhere this info meanwhile here we have /photos/[thumbs,encoded_videos,library,upload]
My library path is sorted by date and upload is like hashed and tree-sorted by hex values of the file hash i guess

Ideally i would like the date setup with the storage label
Thank you :)

**Comment by martabal** [comment]
The upload library is mapped to the `/photos` folder. If you don't use a storage template, Immich will store all your assets in the `upload` subfolder, your thumbs and encoded video to `thumbs` and `encoded_videos`. If you use the storage template, it will store move the assets from `upload` to `library`
