### ISSUE TITLE
CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by BrandonG777** [imagegenius/docker-immich#349]
Receiving the following error when trying to utilize CUDA for machine learning...

CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version

OS: UnRAID 6.12.10
Nvidia Driver: v550.78 (Quadro RTX 4000 should fine for CUDA 12)
Immich: v1.102.3

**Comment by martabal** [comment]
Did you correctly setup the container ? https://github.com/imagegenius/docker-immich?tab=readme-ov-file#nvidia-hardware-acceleration

**Comment by BrandonG777** [comment]
no. had a white space preceding one of my variables.. 🤦‍♂️

all good now!
