### ISSUE TITLE
Port mappings wrong

### ISSUE THREAD

**Issue by User19818** [imagegenius/docker-immich#350]
I followed Spaceinvader One's install instructions for install. PostgreSQL_Immich is up and running but I get an execution error when I try to run Immich. Unraid shows port mappings as 0.0.0.0:8080/TCP-->0.0.0.0:8080.

I checked my settings but can't seem to find the error in my docker configuration.

**Comment by hydazz** [comment]
Mind providing us with said execution error?

**Comment by User19818** [comment]
Fixed on reboot
