### ISSUE TITLE
Allow to specify the host/ports

### ISSUE THREAD

**Issue by mpapamanz** [imagegenius/docker-immich#359]
Hello,
it would be great to be able to control the Host/port that immich and the ml use

Immich has similar env https://immich.app/docs/install/environment-variables#ports

Something like creating and being able to set these 4 environment variables
IMMICH_HOST (currently set to 0.0.0.0)
IMMICH_PORT (currently set to 8080)
IMMICH_ML_HOST (Currently set to 0.0.0.0)
IMMICH_ML_PORT (Currently set to 3003)

**Comment by hydazz** [comment]
You should be able to just add these variables and set them to what you desire?

**Comment by mpapamanz** [comment]
These variables don't exist. In the Docker compose by Immich there are only IMMICH_HOST and IMMICH_PORT but in docker-immich none of them exist.
I edited the issue clarifying that they need to be created, thank you for flagging!

**Comment by hydazz** [comment]
why not use [IMMICH_MACHINE_LEARNING_URL](https://github.com/imagegenius/docker-immich/blob/0c07c89d6b8201b2342d1efd1191eb3a30a04054/Dockerfile#L14) and [SERVER_PORT](https://github.com/imagegenius/docker-immich/blob/0c07c89d6b8201b2342d1efd1191eb3a30a04054/Dockerfile#L19). @martabal I dont see a way to specify a sort of `IMMICH_HOST`?

**Comment by martabal** [comment]
Currently, there's no way to specify the host or the port for the machine learning.

Here's how we start the machine-learning service:
```bash
exec \
    cd /app/immich/machine-learning s6-setuidgid abc \
       gunicorn app.main:app \
		....
        -b 0.0.0.0:3003 \
        ...
```
Here's how it's done upstream:

```bash
gunicorn app.main:app \
	...
	-b "$IMMICH_HOST":"$IMMICH_PORT" \
	...
```

We can probably have different envs for the machine learning

**Comment by hydazz** [comment]
`IMMICH_MACHINE_LEARNING_URL` is for listening?

**Comment by martabal** [comment]
> `IMMICH_MACHINE_LEARNING_URL` is for ml service?

Not really, it's the env used by the microservices to communicate with the machine-learning
