### ISSUE TITLE
CORS?

### ISSUE THREAD

**Issue by astjohn** [imagegenius/docker-immich#361]
Hi there,

I'm trying to use [Immich Duplicates](https://github.com/agross/immich-duplicates). On previous docker images, I was able to update nginx config to allow for CORS requests. Am I correct that the docker image is now running something called Gunicorn instead of nginx? Is there a way to enable CORS requests so I can restart removing the thousands of duplicates that I have queued up? Any insight is greatly appreciated.

Thanks!

**Comment by martabal** [comment]
Have you correctly setup the CORS as described in the README?

**Comment by astjohn** [comment]
@martabal - thanks for getting back to me. [I don't see much here](https://github.com/imagegenius/docker-immich/blob/main/README.md) about reverse proxies?

I'm using the image verbatim in Unraid (not using any variant of docker-compose or the like) which provides a facility to run containers and expose the ports through the operating system to the local network. I then use cloudflare and `jlesage/nginx-proxy-manager` to expose Immich to the outside world. That said, even on the local network, I am unable to connect due to CORS blocking the requests. So regardless of whether I'm on the local network or connecting from outside, Immich's server seems to be blocking the CORS requests.

On previous versions of this image (again, not historically using docker-compose), I was able to adjust the nginx config that seemed to be bundled within the docker image. Is that setup no longer the case?

Thanks.

**Comment by martabal** [comment]
> [I don't see much here](https://github.com/imagegenius/docker-immich/blob/main/README.md) about reverse proxies?

I'm talking about the section 5. described in the [agross/immich-duplicates ](https://github.com/agross/immich-duplicates) README

> Is that setup no longer the case?

Yes, we no longer require nginx, since last year.

That said, next Immich version will have an integrated tool to find/delete duplicates.

**Comment by astjohn** [comment]
Ah, gotcha. Yes, the dupes is referencing reverse proxies that can be set up in front and I suppose it was convenient to edit nginx that was part of the container. I'll just wait for the integrated tool. That will be a great feature addition. Thanks!

**Comment by ilomon10** [comment]
I cannot able to make request from different domain, it always sent `OPTION` method, and the immich not resolve that method.

SOLVED, just pass some header with `nginx proxy manager`:

<img width="506" height="768" alt="Image" src="https://github.com/user-attachments/assets/bd5cc694-470b-46cd-b104-32ef6e7c3210" />

```conf
# Handle preflight OPTIONS requests
if ($request_method = OPTIONS) {
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'X-Api-Key, User-Agent, Content-Type' always;
    add_header 'Access-Control-Max-Age' 1728000;
    add_header 'Content-Type' 'text/plain; charset=UTF-8';
    add_header 'Content-Length' 0;
    return 204;
}

# Handle actual requests (GET, POST, etc.)
# Use a more appropriate way than broken '|' syntax
# Typically placed in the location block instead of using 'if'
add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'X-Api-Key, User-Agent, Content-Type' always;
add_header 'Access-Control-Max-Age' 1728000;
```
