### ISSUE TITLE
Error: "'3003'" is not a valid port number in docker logs after update to v1.105.1-ig282 from v1.105.1-ig281

### ISSUE THREAD

**Issue by Deathproof76** [imagegenius/docker-immich#362]
Updated to v1.105.1-ig282 from v1.105.1-ig281 and suddenly my docker logs are flooded with:

```
immich      | 
immich      | Error: "'3003'" is not a valid port number.
immich      | 
immich      | 
immich      | Error: "'3003'" is not a valid port number.
immich      | 
immich      | 
immich      | Error: "'3003'" is not a valid port number.
```
right after startup. The error is gone when going back to v1.105.1-ig281.

**Comment by HippoBloke** [comment]
Ditto here - how do I roll back on Unraid

Thanks

**Comment by HippoBloke** [comment]
App seems to be looking for 127.0.0.1:3003

After rollback the log shows successful connection on 0.0.0.0:3003

Hippo

**Comment by emaspa** [comment]
> MACHINE_LEARNING_PORT

Can confirm this fixed the issue for me too, also only setting host and no port would still produce the same error in logs, really need to set both.

**Comment by HippoBloke** [comment]
Fixed here too

**Comment by jclendineng** [comment]
> It's fixed by setting env for both
> 
> ```
>       - MACHINE_LEARNING_HOST=127.0.0.1
>       - MACHINE_LEARNING_PORT=3003
> ```
> 
> If only port is set, the logs will complain about not being able to connect to 0.0.0.0
> 
> most likely due to an incorrect notation of the new env vars from [1047230](https://github.com/imagegenius/docker-immich/commit/1047230754ed4dc2d9cfc0b4d219ed72c7db25bc) #360

This did not work for me this morning, I had to use the IP of the Immich instance

**Comment by martabal** [comment]
Sorry guys for the inconvenience, #363 will fix it

**Comment by eLpresidente87** [comment]
Fixed it ! .. Thanks..

for unraid user, here is the how to

https://forums.unraid.net/topic/166039-immich-port-3003-is-not-a-valid-port-number/

**Comment by martabal** [comment]
> Fixed it ! .. Thanks..
> 
> for unraid user, here is the how to
> 
> [forums.unraid.net/topic/166039-immich-port-3003-is-not-a-valid-port-number](https://forums.unraid.net/topic/166039-immich-port-3003-is-not-a-valid-port-number/)

That's correct, but you can just pull the new image (just press "force update" if you are an unraid user) to fix it :smile:

**Comment by eLpresidente87** [comment]
> > Fixed it ! .. Thanks..
> > for unraid user, here is the how to
> > [forums.unraid.net/topic/166039-immich-port-3003-is-not-a-valid-port-number](https://forums.unraid.net/topic/166039-immich-port-3003-is-not-a-valid-port-number/)
> 
> That's correct, but you can just pull the new image (just press "force update" if you are an unraid user) to fix it 😄

Oh I didn't know that they where so fast with updating it

**Comment by martabal** [comment]
Who are they'? Docker on Unraid is like all Linux machines. As soon as the docker image is published to the registry, the image is available on Unraid, no one needs to push/approve it. The only thing unraid does is:
- automatically and regularly check if a new version is available
- provide templates, which is a fancy way of describing how to run a Docker image

**Comment by eLpresidente87** [comment]
> Who are they'? Docker on Unraid is like all Linux machines. As soon as the docker image is published to the registry, the image is available on Unraid, no one needs to push/approve it. The only thing unraid does is:
> 
> * automatically and regularly check if a new version is available
> * provide templates, which is a fancy way of describing how to run a Docker image

with "they" i ment the Immich Creators not unraid, i am aware of unraid is like a GUI for these things.. :)

**Comment by martabal** [comment]
Oh sorry for the misunderstanding, it wasn't an upstream issue, it was introduced directly in this project with #360, and we can all thank @hydazz to be reactive

**Comment by eLpresidente87** [comment]
@hydazz you are the man.. thank you all for your amazing work
