### ISSUE TITLE
trying to install on docker in Open Media Vault

### ISSUE THREAD

**Issue by jchoneandonly** [imagegenius/docker-immich#365]
see title. i cant seem to get it running on open media vault.  keep getting error. 

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/immich /immich .yml' --env-file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/immich /immich .env' --env-file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/global.env' up -d 2>&1':  redis Pulling
 immich Pulling
 postgres14 Pulling
 redis Error context canceled
 postgres14 Error context canceled
no matching manifest for linux/arm/v7 in the manifest list entries

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/immich /immich .yml' --env-file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/immich /immich .env' --env-file '/srv/dev-disk-by-uuid-b18d49fb-0be0-4138-9164-07cbdb403e94/compose/global.env' up -d 2>&1':  redis Pulling
 immich Pulling
 postgres14 Pulling
 redis Error context canceled
 postgres14 Error context canceled
no matching manifest for linux/arm/v7 in the manifest list entries in /usr/share/openmediavault/engined/rpc/compose.inc:805
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(622): OMVRpcServiceCompose->{closure}()
#1 /usr/share/openmediavault/engined/rpc/compose.inc(780): OMV\Rpc\ServiceAbstract->execBgProc()
#2 [internal function]: OMVRpcServiceCompose->doCommand()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#6 {main}

**Comment by martabal** [comment]
armv7 is not a supported architecture
