### ISSUE TITLE
Port 8080 No Longer Responsive

### ISSUE THREAD

**Issue by maxexcloo** [imagegenius/docker-immich#372]
Since a few days ago Immich wasn't responding, I checked the logs and it seems to be listening on port 3001 now, when I changed the docker port, it worked - does anyone have any ideas how this happened?

Appreciate any help ~

**Comment by martabal** [comment]
Can you share your Immich setup ? (docker run command or docker-compose.yml or unraid template...)

**Comment by maxexcloo** [comment]
Sure, should have done that earlier!

```networks:
  default:
    external: true
    name: caddy
services:
  immich:
    depends_on:
      - postgres
      - redis
    environment:
      DB_DATABASE_NAME: ${WEBSITE_DATABASE_USERNAME}
      DB_HOSTNAME: postgres
      DB_PASSWORD: ${WEBSITE_DATABASE_PASSWORD}
      DB_USERNAME: ${WEBSITE_DATABASE_USERNAME}
      REDIS_HOSTNAME: redis
      TZ: ${DEFAULT_TIMEZONE}
    image: ghcr.io/imagegenius/immich
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 3001}}"
    restart: unless-stopped
    volumes:
      - /Volumes/Media/Pictures/Pictures:/import:ro
      - immich_data:/config
      - immich_photos:/photos
  postgres:
    environment:
      POSTGRES_PASSWORD: ${WEBSITE_DATABASE_PASSWORD}
      POSTGRES_USER: ${WEBSITE_DATABASE_USERNAME}
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
volumes:
  immich_data:
  immich_photos:
  postgres_data:
```

Weirdly it seems to work fine once I change the port to 3001, I didn't change anything (but I do have watchtower enabled...)

**Comment by martabal** [comment]
Can you make sure you have the latest Docker image and restart the Immich container? Once initialized, one of the last lines in the docker logs corresponds to the port on which Immich listens for connections.

**Comment by AlesZurek** [comment]
Hey, I believe I had similar issue from yesterday. Today I resolved it with adding line
` - IMMICH_PORT=8080` under environment part

In breaking change there is mentioned

> SERVER_PORT, MICROSERVICES_PORT, and MACHINE_LEARNING_PORT were renamed to IMMICH_PORT

And when I was checking in portainer there has been env variable SERVER_PORT but no IMMICH_PORT.
I was pulling this repo yesterday and also today and it didn't work untul I added that one line (manually specified that environmental variable)

**Comment by martabal** [comment]
Weird, this variable is already set 🤔

https://github.com/imagegenius/docker-immich/blob/93592b2fe8f661220fb63a6daad08401afff477c/Dockerfile#L17

**Comment by AlesZurek** [comment]
Maybe I was doing something wrong on my side, I can try to remove my change and try it again. I was running 
`docker-compose pull` and `docker-compose up -d` that should be enough right?

**Comment by sendev1** [comment]
Thank you. I had port setup as follows
```
ports:
      - 8081:8080
  ```

and i pulled recent image and it broke my setup. I was able to find your post and changed contained port to 3001 and now i am able to access immich. It seems this is breaking change.

**Comment by AlesZurek** [comment]
I can confirm that in my case I have also custom ports config
```
    ports:
      - 8088:8080
```

So maybe it is connected that normally it works only with this override it cause troubles.

**Comment by maxexcloo** [comment]
Not sure if I should close this - do I need to set the env var, I guess the issue is that this didn’t apply as default suddenly.

**Comment by AlesZurek** [comment]
Like I am not sure why it is happening, if you also don't know why it is happening then I suppose we can close it as there is only few of us affected and there is workaround to get it working described here (define the environmental variable).
So from my perspective feel free to close it.
