### ISSUE TITLE
Change the storage folder to external mounted drive

### ISSUE THREAD

**Issue by cktechie2012** [imagegenius/docker-immich#376]
Hi

I have updated the .env for UPLOAD_LOCATION=/mnt/externaldrive/photos, which is a SSD drive with 1TB storage

However when I check the immich web portal, it still does not point to the external drive for the photos uploaded.

can you please suggest.

**Comment by hydazz** [comment]
you have setup your own .env and specified that in the docker-compose?
have you mounted `/mnt/externaldrive/photos` inside the container?

**Comment by cktechie2012** [comment]
you have setup your own .env and specified that in the docker-compose? -- I used the .env file from the repository, and edited the location.
have you mounted /mnt/externaldrive/photos inside the container? -- I have added the location in docker compose file as well as .env. How else does this need to be done?

**Comment by cktechie2012** [comment]
you have setup your own .env and specified that in the docker-compose? -- I used the .env file from the repositry, and edited the location.
have you mounted /mnt/externaldrive/photos inside the container?

**Comment by cktechie2012** [comment]
<img width="330" alt="image" src="https://github.com/imagegenius/docker-immich/assets/51134550/ed0a6e69-0cc8-4624-a8b7-848e7289f2e6">

**Comment by cktechie2012** [comment]
<img width="407" alt="image" src="https://github.com/imagegenius/docker-immich/assets/51134550/41c8151e-ddc0-4263-aa35-3d76e4622262">
this is .env

**Comment by cktechie2012** [comment]
I think I got what you meant, and have it resolved/

I moved the immich docker file and .env to the Storage drive and started it there. 

the database and files are not getting backed in the storage itself

**Comment by cktechie2012** [comment]
resolved
