### ISSUE TITLE
Library watching (EXPERIMENTAL)

### ISSUE THREAD

**Issue by mxm199** [imagegenius/docker-immich#377]
Hello everyone, tell me, does anyone have this function working at all? 
The folder is mounted as "d:/dcim:/mnt/media/dcim" (I use Windows Docker Desktop).
The Library itself is displayed normally, scanned and processed.
New files are found during periodic scanning, but automatic detection does not want to work in any way. Of course, I understand that this is an experimental function, but maybe someone has achieved operability?

![image](https://github.com/imagegenius/docker-immich/assets/133875469/3a85a8eb-3c07-4b9f-8281-3d28498562af)
![image](https://github.com/imagegenius/docker-immich/assets/133875469/db70b8af-9b91-4cd6-80a2-b73eef99d696)
![image](https://github.com/imagegenius/docker-immich/assets/133875469/5480b205-b52b-43e5-9b74-1497312aecb1)

**Comment by hydazz** [comment]
seems like more of an [upstream](https://github.com/immich-app/immich) problem, perhaps open an issue there 🙂
