### ISSUE TITLE
Missing 'error' handler on this Redis client

### ISSUE THREAD

**Issue by Allram** [imagegenius/docker-immich#38]
Hello,

I get "alot" of notifications in the log that the error handler on the Redis client is missing.
Is this something you are aware of? :)

Running Redis v7 connected trough Unix socket.

`missing 'error' handler on this Redis client`

Edit: Maybe this was fixed in Redis\Client 1.5.4?

**Comment by hydazz** [comment]
is this an immich issue or a container issue?

**Comment by martabal** [comment]
I never had this error.

> missing 'error' handler on this Redis client

Is this an Immich error ? Does Redis log errors on its side ?

**Comment by hydazz** [comment]
@martabal jinx

**Comment by Allram** [comment]
Not sure if it's immich or container issue.
I run this on UnRaid and it shows up in the imagegenious/Immich docker container logs :P

**Comment by martabal** [comment]
And if you try with TCP rather than unix socket ?

**Comment by Allram** [comment]
Getting the same with TCP socket.
Are you guys Running Redis v7? or might that be my problem..

**Comment by martabal** [comment]
I'm running Redis latest (v7) on Unraid just like you

**Comment by Allram** [comment]
I will just close this issue, i don't think it matter that the log says that the error handler is missing.
Redis does not log any errors as far as i can see.
