### ISSUE TITLE
New docker images

### ISSUE THREAD

**Issue by martabal** [imagegenius/docker-immich#392]
Hello everyone!

We are adding cuda and openvino support for GPU acceleration. Until now, if you wanted to have GPU acceleration for your Nvidia GPU, you had to install a bunch of dependencies during the runtime. Everytime you restarted your Immich container, you installed/checked the dependencies needed for the GPU acceleration. This could take several minutes, was inefficient and could lead to dependency installation issues. It's no more the case, all dependencies are now installed during the image build.

We don't want to ship a 3 GB docker image for people who don't use machine learning, so we are now maintaining 4 different versions of Immich:
- `noml`: (stands for "no machine-learning") Latest version of Immich without machine-learning
- `latest`: Latest version of Immich (obviously)
- `cuda`: Latest version of Immich and supports cuda for GPU acceleration (Nvidia GPUs) 
- `openvino`: Latest version of Immich and supports openvino for GPU acceleration (Intel GPUs)

To use one of these versions, simply replace the docker tag with that version (for exemple `ghcr.io/imagegenius/immich:cuda`)

To use `cuda` or `openvino` versions, please follow the instructions [here](https://github.com/imagegenius/docker-immich?tab=readme-ov-file#hardware-acceleration).

If you were using cuda for GPU acceleration, the `MACHINE_LEARNING_GPU_ACCELERATION` env is no longer used.

> [!WARNING]
> If you were using cuda, remove the `cuda` folder in `/config/machine-learning`

**Comment by MoSattler** [comment]
Hi, just tried out the `cuda` image. For some reason, jobs in that image do not work. Not even jobs unrelated to ML (like generating thumbnails). Logs do not show anything, it just puts the job in waiting, and never starts.
