### ISSUE TITLE
Jobs do not start

### ISSUE THREAD

**Issue by MoSattler** [imagegenius/docker-immich#393]
On a fresh install, jobs do not start. E.g. when clicking "GENERATE THUMBNAILS", it will put the job into waiting and not do anything. 

Could it be possibly related to https://github.com/immich-app/immich/discussions/10766#discussioncomment-9939464 and some upgrade step was missed?

**Comment by martabal** [comment]
The issue you linked is related to the docker-compose method which is a different way to deploy Immich, so it's completely unrelated. Can you share your setup and your docker logs?

**Comment by MoSattler** [comment]
I used the preconfigured package in the unraid App Store. 

After having a few more issues, I switched to the official docker builds in the end, which work for me. So I dont have access to the logs anymore. 

Since this is not relevant anymore, I will close this issue!
