### ISSUE TITLE
Using the Unraid official docker container maintained by imagegenius, newest version have no thumbnails of videos.

### ISSUE THREAD

**Issue by superdong69** [imagegenius/docker-immich#401]
It's been said to fix this:
"You probably didnt remove the command: ['start.sh', 'immich'] from your compose. So it's trying to use the external microservices container for generating previews."

Being in Unraid, there is no docker-compose. Can we get this fixed in the "Official" Unraid app?

**Comment by hydazz** [comment]
Have you got any environment (which docker tag you're using) information or error logs to provide? Where did you get that quote from? - `"You probably didnt remove the command: ['start.sh', 'immich'] from your compose. So it's trying to use the external microservices container for generating previews."` does not remotely apply on a container context
