### ISSUE TITLE
CA Says Apply Update, but won't update

### ISSUE THREAD

**Issue by marcstaubitz** [imagegenius/docker-immich#409]
Running the CA Immich AIO and it says I have an update available. But regardless of how many times I run through the update, I am not getting any version higher than 1.103.1. Unfortunately my iPhone app needs at least 1.106 to resume uploading, so in a bit of bind here.

**Comment by hydazz** [comment]
what tag are you using? can you provide the full `ghcr.io/imagegenius/immich:...` value, and a screenshot of the update popup

**Comment by marcstaubitz** [comment]
Somehow the tag got deleted, so it's working now.
