### ISSUE TITLE
New storage locations

### ISSUE THREAD

**Issue by Backslashh** [imagegenius/docker-immich#41]
To align with the new storage options in immich (separation of library, profile, thumbs, encoded-video) can the image support breaking the storage locations out so we can assign things like thumbs and encoded-video to different backend locations (SSD disks, etc)?

**Comment by martabal** [comment]
Yep, now you can totally mount `/photos/thumbs`, `/photos/encoded-videos` and `/photos/profile` to folders on your ssd. However this will affect only new uploaded pictures and videos. Previous videos and pictures are left untouched.

**Comment by Backslashh** [comment]
Nice. Just did this and then ran the migration jobs. Works a treat. Thank you.
