### ISSUE TITLE
unRAID - After last few updates (:cuda), Container takes a long time to start

### ISSUE THREAD

**Issue by Tyree** [imagegenius/docker-immich#415]
Since the container was split up into the separate tags for GPU acceleration, it take a long time for the container to start after an update. I just timed it and it took 3.5 minutes for the logs to move past the /IG/ linuxserver.io splash.
I am using the :cuda tag.
Are there processes starting in the background that don't log to this screen using this version?
Everything seems to be working fine after it finally starts (so not a huge problem), but it didn't start acting this way until the change to the versions. Even though I still had GPU acceleration set up before.
Thanks!

**Comment by hydazz** [comment]
should be fixed by https://github.com/imagegenius/docker-immich/pull/410

**Comment by Skylinar** [comment]
Seems like I'm facing the same issue. My container took around 10 mins to start up.
