### ISSUE TITLE
App will not start 

### ISSUE THREAD

**Issue by soana** [imagegenius/docker-immich#417]
Using this docker image on unraid server 6.12.11. 
After doing a  docker restart today immich does not seem to start anymore.
All I get is the  following in the docker log:
```
[mod-init] Running Docker Modification Logic
[mod-init] Adding imagegenius/mods:universal-redis to container
[mod-init] imagegenius/mods:universal-redis at sha256:d79cc7c55bbb144e663xxxxxxxxxxxxxxxxxxxxx3ec42361fa3ac829f8eca48a9d7b1d43 has been previously applied skipping
[migrations] started
[migrations] no migrations found

╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
```
No other messages to help diagnose the issue.
Please let me know where I should look for clues on how to fix this.

**Comment by cpuks** [comment]
You need to revert to previous working tag - image: ghcr.io/imagegenius/immich:v1.108.0-ig305 - that's the one working and ig306 has same problems on my system. 
So to confirm - ig306 gives me exactly same error.
