### ISSUE TITLE
1.109.0 image won´t start (no logs)

### ISSUE THREAD

**Issue by Chamber3399** [imagegenius/docker-immich#419]
Hi,

Recently updated to 1.109.0, but the immich server won´t start now. When checking the logs, I only get the following

`[migrations] started
[migrations] no migrations found

╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
`

I tried:

- Restarting the docker image and the server it is running on
- Uninstalling and reinstalling the image

Is this a common issue with the latest update?

database info:

- tensorchord/pgvecto-rs:pg15-v0.2.0 docker image
- Redis docker image
- Unraid 6.12.11

**Comment by Chamber3399** [comment]
Also, the image version is :latest, not running on any gpu

**Comment by Chamber3399** [comment]
Figured it out, after running the new permissions tool in unraid the server seems to start again

**Comment by Chamber3399** [comment]
Apparently the server did not start due to folder permissions in unraid not being set correctly, running ¨new permissions" tool fixed it

**Comment by Chamber3399** [comment]
Apparently the server did not start due to folder permissions in unraid not being set correctly, running ¨new permissions" tool fixed it

**Comment by 3rdStng** [comment]
New Permisisons (disks) and Docker Safe Permissions didn't do it for me. Looks like something possibly related to unRAID 6.12.11, My docker was perfectly fine on 6.12.10 and now doesn't get past the IG screen. Anything else you did or that I can try?

**Comment by hydazz** [comment]
we pushed out a change to NOT apply permissions on startup, are you using the latest image?

if your seeing these issues please set `S6_VERBOSITY=2` and post those logs

**Comment by hydazz** [comment]
fixed in https://github.com/imagegenius/docker-immich/commit/1112d7cffbae00195804df81315bc820d6932d60
