### ISSUE TITLE
immich CLI on unraid 

### ISSUE THREAD

**Issue by revoltn** [imagegenius/docker-immich#42]
I have run "npm i -g immich" to install the cli.

immich upload --key xxxxxxxxxxxxxx --server http://192.168.2.110:8080/api --recursive /photos-old/  returns the error:
error: unknown command 'upload'

runniung the command  find -name immich -print returns the foillowing (Ignorning the access errors)

./run/immich
find: ‘./sys/kernel/slab’: Input/output error
./usr/bin/immich
./usr/lib/node_modules/immich
./usr/local/bin/immich
./app/immich
./app/immich/server/dist/apps/cli/apps/immich
./app/immich/server/dist/apps/immich
./app/immich/server/dist/apps/immich/apps/immich

**Comment by hydazz** [comment]
there are 2 commands with the `immich` name:

```
# /usr/local/bin/immich
Usage: immich [options] [command]

Options:
  -h, --help              display help for command

Commands:
  reset-admin-password    Reset the admin password
  enable-password-login   Enable password login
  disable-password-login  Disable password login
  list-users              List Immich users
  help [command]          display help for command
```

```
# /usr/bin/immich
Usage: immich [options] [command]

Immich command line interface

Options:
  -V, --version                output the version number
  -h, --help                   display help for command

Commands:
  upload [options] [paths...]  Upload assets to an Immich instance
  help [command]               display help for command
```
