### ISSUE TITLE
how to make external libraries read-only

### ISSUE THREAD

**Issue by ctny** [imagegenius/docker-immich#425]
I am using immich v1.111.0 on unraid, the docker images is by imagegenius. 

I have 400,000 family photos that I want to share as read-only to all family members. Read-only, so they are not accidentally deleted, especially by the kids. 

My plan is to create 1 family account, then create the external libraries under this family account, and let everyone login as the same account. I don't care about photo backups from the phones, this is just for showing the photos on the server.

Can someone suggest how to mount the external libraries as read-only? Is there a docker parameter? I am new to unraid and docker, would appreciate step by step instruction, thanks.

**Comment by ctny** [comment]
I was able to find the solution. 

As reference to others, for the "Path: /libraries:" parameter, click the "EDIT" button, and you can set the path as read-only. When trying to delete a photo, the log shows the photos cannot be deleted, as expected.

[Nest] 259  - 08/03/2024, 9:00:50 PM    WARN [Microservices:StorageService] Unable to remove file from disk
[Nest] 259  - 08/03/2024, 9:00:50 PM    WARN [Microservices:StorageService] Error: EROFS: read-only file system, unlink '/libraries/[photo path]'

**Comment by skret028** [comment]
BTW,if you use docker-compose,you can also edit the volume config as below:
    volumes:
      - path_to_appdata:/config:rw
      - path_to_photos:/photos:rw
      - path_to_libraries:/libraries:ro

rw refers to readwrite
ro refers to readonly
