### ISSUE TITLE
/photos and /app/immich/server/upload/

### ISSUE THREAD

**Issue by paulmorabito** [imagegenius/docker-immich#426]
Hi,

I migrated my Immich instance from another older NAS to Unraid and when I set up the Immich App/container, I mistakenly didn't map my previous Immich photos path to /photos. Instead, I used the paths from my previous config using another container image. Now, when I start Immich the photo directory needs to be mounted to /app/immich/server/upload/ or else they are not detected. I have correctly mapped to /photos too but its not being detected or used.

As a side effect, the disk usage/size is also incorrect because its showing the container disk size (20GB) and not the disk where the photos are stored.

Is there anything I can do to point it to /photos? I can't see an env or other config file in the app data folder.

Many thanks in advance.

**Comment by hydazz** [comment]
I believe the full paths of the images are stored in the database, so youll have to modify each reference to the old paths to the new one (pretty easy to do) but you should just be able to mount your photos as you had before, when you do a bind mount the container size should not increase, where are you getting that 20GB figure?

**Comment by paulmorabito** [comment]
OK, I guess its some SQL? or is there a tool for it?

re: mount. Immich is listing the max capacity as 20GB (the same as i get for / when i do a  "df -h" in the container) I guess this is because its not detecting its a different volume.
