### ISSUE TITLE
 [Nest] Startup Warning - The module "ClsModule" is taking xx.xxms to serialize

### ISSUE THREAD

**Issue by masterwishx** [imagegenius/docker-immich#428]
Using lasted version in Unraid

on startup have warning for long time :

https://github.com/nestjs/nest/issues/12738

![image](https://github.com/user-attachments/assets/4cd1d11a-5ad5-4719-97b4-5b4fd2eeead6)

![image](https://github.com/user-attachments/assets/7577af83-fbd8-4cf8-b4c7-5f460f276283)

**Comment by hydazz** [comment]
does it effect the use of the app? it does not appear to hinder the startup times at all

**Comment by masterwishx** [comment]
> does it effect the use of the app? it does not appear to hinder the startup times at all

I think no, also today after restarted I can't see it, all fine, can close issue for now

**Comment by masterwishx** [comment]
@hydazz it seems I have it on unraid server boot but if restart container it's gone.
Not sure if I need reopen issue?

**Comment by hydazz** [comment]
whats specs is your unraid box? could be running out of CPU cycles on boot, causing 'lag'

**Comment by masterwishx** [comment]
> whats specs is your unraid box? could be running out of CPU cycles on boot, causing 'lag'

Maybe, I will try to check not shure how
I5-4440 4core, 24g mem have about 70 containers running...

**Comment by hydazz** [comment]
I would 100% say you are pushing that CPU way to far loading up 70 containers on boot
