### ISSUE TITLE
Feature request: failed access logging

### ISSUE THREAD

**Issue by Davo1624** [imagegenius/docker-immich#43]
Currently when a failed access attempt is logged it is logged to the container STDOUT which makes it difficult for fail2ban and similar apps to parse the log and ban the ip after too many failed attempts. It would be easier if access attempts were logged to the current /config/log/nginx/error.log or similar

**Comment by hydazz** [comment]
we can do something like https://github.com/hydazz/docker-immich/commit/df0701804683f258837ff0bd67693ad554f6b45c

@Davo1624 is talking about failed login attempts send by immich, not nginx

**Comment by hydazz** [comment]
does nginx not spit out an error message if authentication fails?

**Comment by Davo1624** [comment]
> does nginx not spit out an error message if authentication fails?

No, the nginx error log does not record failed logins, only the container log does

**Comment by hydazz** [comment]
do you suggest piping (`>`) the output of the services into `.log` files, and having logrotate rotate them?

**Comment by Davo1624** [comment]
I honestly don't how enough about the underlying code but that sounds correct.

**Comment by hydazz** [comment]
apologies for the delay, perhaps try https://github.com/imagegenius/docker-immich/pull/177 once it finishes building, the server logs will be outputed to the console and `/config/logs/immich/server.log`
