### ISSUE TITLE
Can't access Immich WebUI - Having Port issues (I think?) on Unraid

### ISSUE THREAD

**Issue by dbell440** [imagegenius/docker-immich#430]
I am trying to get Immich up and running and have followed all the Spaceinvader One's instructions from his videos but after install is done I go to access the WebUI and get an error that it can't be reached. I did run into one issue that the default container port (8080) is the same as Krusader. I changed the port to 8090 and it said it was successful, but as I mentioned, I can't access the web UI.  When I look at the docker container I am guessing my issue is with the port mapping, but I just don't know how to fix this. I have attached system log and a text copy of the immich log as well. 
![Dockers](https://github.com/user-attachments/assets/6973b959-5b9d-4c50-a042-8e03649eb5dc)
[immich.log.txt](https://github.com/user-attachments/files/16711536/immich.log.txt)

[mediamadness-syslog-20240822-0246.zip](https://github.com/user-attachments/files/16711539/mediamadness-syslog-20240822-0246.zip)

**Comment by BusterDogg** [comment]
Port 6379 is used typically by Redis. Do you have a Redis DB running?

**Comment by dbell440** [comment]
Umm... so this may be a dumb question... how do I tell?

**Comment by dbell440** [comment]
So I believe I do have Redis running now and have updated Immich, still no luck:
![image](https://github.com/user-attachments/assets/7167c7f2-17ce-4d3a-94c7-3ccde2e829a1)

**Comment by hydazz** [comment]
set your redis url to the ip of your unraid box, from your logs its trying to access redis at localhost `127.0.0.1`, which is confined to inside the immich container, and redis is running outside of it

**Comment by dbell440** [comment]
I was wondering about that, but I cannot see where to make that change. Is that in Immich or in Redis that I would change that? Sorry if this is a dumb question.

**Comment by dbell440** [comment]
Finally fixed, somehow the postgres password got changed.
