### ISSUE TITLE
The WebUI port for listening inside the container is not customizable on Unraid

### ISSUE THREAD

**Issue by yzhEric** [imagegenius/docker-immich#434]
I installed immich on my Unraid NAS by Unraid CA but couldn't connet to WebUI, then I found that the ENV parameter "WebUI" does not change the port for listening. It only expose the [container's A port] to [host's A port] if I set the "WebUI" to A(like 8081, for example), which dosen't make any sense.
The port for listening inside the container is always 8080, which I found by checking the log:
```os
LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:8080 [v1.114.0] [PRODUCTION] 
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
```
So I deleted the original "WebUI" and made a new one to expose 8080 to host's A port then it worked.

**Comment by martabal** [comment]
What's your network type?

**Comment by martabal** [comment]
What network type are you using. The WebUI is not an env, it's a port mapping.

**Comment by yzhEric** [comment]
I'm using bridge.
I know it's a port mapping, but setting it to like 7890 only does this `-p 7890:7890` rather than `-p 7890:8080`.
Because the port for listening is always 8080, setting WebUI to 7890 dosen't make any sense.

**Comment by martabal** [comment]
If you want to change the port Immich is listening on, you can do it with the env `IMMICH_PORT`

**Comment by yzhEric** [comment]
Thank you, I understand that. I can't reproduse the error, so maybe i do some wrong steps. Anyway, thank you for replying.
