### ISSUE TITLE
Machine Learning - Connection Refused

### ISSUE THREAD

**Issue by not-just-jack** [imagegenius/docker-immich#436]
Hoping someone could point me in the right direction. I've reinstalled twice with the same result. It appears as though nothing associated with Machine Learning is being installed. The Machine Learning folder within appdata is empty and when attempting to run any jobs that use machine learning, I receive an error message in the logs associated with the connection being refused.  Below is an example. 
```
[Nest] 282  - 09/19/2024, 6:01:23 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request to "http://192.168.1.31:3003" failed with Error: connect ECONNREFUSED 192.168.1.31:3003
[Nest] 282  - 09/19/2024, 6:01:23 PM   ERROR [Microservices:JobService] Error: Machine learning request to "http://192.168.1.31:3003" failed with Error: connect ECONNREFUSED 192.168.1.31:3003
    at /app/immich/server/dist/repositories/machine-learning.repository.js:19:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.detectFaces (/app/immich/server/dist/repositories/machine-learning.repository.js:33:26)
    at async PersonService.handleDetectFaces (/app/immich/server/dist/services/person.service.js:280:52)
    at async /app/immich/server/dist/services/job.service.js:148:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

**Comment by hydazz** [comment]
what tag are you using? looks like somethings also overwriting `IMMICH_MACHINE_LEARNING_URL` as it should be set to `http://127.0.0.1:3003` not `http://192.168.1.31:3003` unless you are using an external machine learning instance

**Comment by not-just-jack** [comment]
> what tag are you using? looks like somethings also overwriting `IMMICH_MACHINE_LEARNING_URL` as it should be set to `http://127.0.0.1:3003` not `http://192.168.1.31:3003` unless you are using an external machine learning instance

Thanks! The docker container has 0.0.0.0 for the Machine Learning URL, but the url setting within Immich was set to 192.168.1.31. I changed it to 127.0.0.1 and the jobs are processing now with no errors.

**Comment by not-just-jack** [comment]
what tag are you using? looks like somethings also overwriting IMMICH_MACHINE_LEARNING_URL as it should be set to http://127.0.0.1:3003 not http://192.168.1.31:3003 unless you are using an external machine learning instance

Thanks! The docker container has 0.0.0.0 for the Machine Learning URL, but the url setting within Immich was set to 192.168.1.31. I changed it to 127.0.0.1 and the jobs are processing now with no errors.
