### ISSUE TITLE
Issue on latest build 1.116.0

### ISSUE THREAD

**Issue by HippoBloke** [imagegenius/docker-immich#438]
Hi all, 

I'm getting the following repeatedly on startup of 1.116.0 and it fails to start - rolled back to v1.115.0 all good - any thoughts ?
```
[Nest] 1471  - 09/26/2024, 6:18:19 PM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at SystemConfigCore.buildConfig (/app/immich/server/dist/cores/system-config.core.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/cores/system-config.core.js:80:35 {
  code: 'ERR_INVALID_URL',
  input: '***.******.***',   ( My URL blanked out )
}
api worker exited with code 1
```

**Comment by HippoBloke** [comment]
I removed the public URL from the setting and it start OK again. Odd as I never had an issue before.

**Comment by dernick79** [comment]
Hey. I had the same issue, but I dont know how to roll Back the docker Container or how to access the Settings to remove the puplic URL. Can someone help?

**Comment by HippoBloke** [comment]
Just edit the docker and add the following 

:1.115.0

So the line reads 

ghcr.io/imagegenius/immich:1.115.0

Remove the URL and then update again.

**Comment by martabal** [comment]
It’s because the URL you provided is invalid and since `v1.116.0`, Immich checks if that URL is valid https://github.com/immich-app/immich/pull/12831

**Comment by HippoBloke** [comment]
It was a valid URL but because it was via cloudflare it wasn't active until Immich had started. I'm moving away from cloudflare anyway. 

Keep up the great work 👍🏻
