### ISSUE TITLE
unraid immich stuck at "Initialized websocket server" after deleting the maching learning models by mistake

### ISSUE THREAD

**Issue by xayane** [imagegenius/docker-immich#440]
Well, after I change the machine learning moedels from buffalo_l to antelopev2.
The immich server seems no response. Then I delete the config folders ( /config/clip and /config/facil recogition) by mistake. 
And I restart the server immediately. Well the damn thing happened. The server stucks at begin, shows below.
![image](https://github.com/user-attachments/assets/72251c95-0fc0-4de2-8706-0862bd87a3a4)

Can anyone help me?

**Comment by martabal** [comment]
Did you try to:
- restart the Immich container ?
- restart your server ?

If this does not work, add this env `IMMICH_LOG_LEVEL=verbose`, restart Immich and share again your logs

**Comment by xayane** [comment]
Thanks for the reply!
 The env 'IMMICH_LOG_LEVEL=verbose' helps me a lot, it shows permission errors.
 The true reason comes from the auto-upgrade of the qnap NAS. Because of the not confirm for the acknowledge of new version, the NFS server and SMB server is not working properly.
Sorry for bothering!
Thanks again.

> Did you try to:
> 
> * restart the Immich container ?
> * restart your server ?
> 
> If this does not work, add this env `IMMICH_LOG_LEVEL=verbose`, restart Immich and share again your logs
