### ISSUE TITLE
Not all files are downloaded from an album

### ISSUE THREAD

**Issue by TallMan206** [imagegenius/docker-immich#448]
Hi,

I have an album with 6 files in it. When I select all, it only download 3 files. The files are ok in Immich, I can see and play them, but when downloaded, I do not get all files. This is an issue, because I want to copy all folders including all files to Google Photo's so that Immich and Google Photos are containing the same files.

What could cause the missing files?
![Schermafbeelding 2024-10-07 151002](https://github.com/user-attachments/assets/3974c737-f225-4bd2-8b40-af4469a48849)
![Schermafbeelding 2024-10-07 151024](https://github.com/user-attachments/assets/578b79b3-a586-4f5a-b11c-1def37ebe38d)

**Comment by martabal** [comment]
If there's no errors in the docker logs, that's an upstream issue
