### ISSUE TITLE
Unraid v 118.1

### ISSUE THREAD

**Issue by blaine07** [imagegenius/docker-immich#450]
Currently have Immich in Unraid using “ ghcr.io/imagegenius/immich:noml”

With v118.1 I am not entirely sure what I need to do with ports?

It says:
![image](https://github.com/user-attachments/assets/f39af211-457a-4929-8c09-abb29d100b5c)

This is what I currently have:
![image](https://github.com/user-attachments/assets/d0c71ca0-7ff1-47f0-a634-be9bd74c5875)

Everything still works so do I still need to change port to 2283? Have NOML version maybe not been updated to v118.1 yet?

Please advise.

**Comment by hydazz** [comment]
There shouldn't be anything you have to do for minor breaking changes, as we can usually control them here and mitigate them.
As for the port, we overwrite it to `8080` anyway, this is just a note for the upstream image users

**Comment by theone11** [comment]
I updated the unraid Immich docker from 0.115 to 0.118 and now get the following error in the log.

**How can I fix this? I haven't changed anything.**

```
Starting api worker
[Nest] 350  - 10/24/2024, 1:17:56 AM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 350  - 10/24/2024, 1:17:56 AM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at buildConfig (/app/immich/server/dist/utils/config.js:116:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/utils/config.js:53:26 {
  code: 'ERR_INVALID_URL',
  input: 'photos.avidank.com'
}
api worker exited with code 1

```
