### ISSUE TITLE
ERROR [ExceptionHandler] password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by dodgemanrt** [imagegenius/docker-immich#451]
I logged into the Postgres docker and ran the command psql -U postgres and I get the message failed: FATAL:  role "postgres" does not exist. Not sure how the user was deleted all of a sudden. How can I add it back ?

**Comment by hydazz** [comment]
Out of scope of our support, but check your postgres container variables, is the 'admin' user set to postgres or immich?
perhaps `psql -U immich`.

Other than that we can't help unfortunately 😕.
