### ISSUE TITLE
Can't connect to server after latest update

### ISSUE THREAD

**Issue by MADM1k33** [imagegenius/docker-immich#453]
After latest update, can't connect to the server, getting "Unable to connect to remote host: Connection refused" on the default 2283 port. Changing the port does not help :(

**Comment by terroreek** [comment]
I am having the same issue, opening the docker logs goes away, I think its because the container is 'boot looping'.

**Comment by hydazz** [comment]
what are your port mappings? port 8080 is used for the webui in this container

**Comment by MADM1k33** [comment]
netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:2283            0.0.0.0:*               LISTEN      107127/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      469/sshd: /usr/sbin
tcp6       0      0 :::2283                 :::*                    LISTEN      107135/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      469/sshd: /usr/sbin

Inside docker-compose.yml
name: immich
services:
  immich-server:
    container_name: immich_server
    ports:
      - 2283:3001

All services inside the container are healthy

docker compose ps
NAME                      IMAGE                                                   COMMAND                  SERVICE                   CREATED        STATUS                    PORTS
immich_machine_learning   ghcr.io/immich-app/immich-machine-learning:release      "tini -- ./start.sh"     immich-machine-learning   14 hours ago   Up 53 minutes (healthy)
immich_postgres           docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:*   "docker-entrypoint.s…"   database                  2 months ago   Up 53 minutes (healthy)   5432/tcp
immich_redis              docker.io/redis:6.2-alpine@sha256:*                     "docker-entrypoint.s…"   redis                     2 months ago   Up 53 minutes (healthy)   6379/tcp
immich_server             ghcr.io/immich-app/immich-server:release                "tini -- /bin/bash s…"   immich-server             14 hours ago   Up 53 minutes (healthy)   2283/tcp, 0.0.0.0:2283->3001/tcp, [::]:2283->3001/tcp

No firewalls installed, just a clean debian distro. Everything worked before the update 🤷‍♂️

**Comment by MADM1k33** [comment]
Update:

Cleared all the iptables rules, recreated them by restarting Docker - now i can connect to 2283 port using 127.0.0.1, but it gives zero data. Connect using eth01 IP is still refused, even from the machine where Immich is based:

root@immich:~/immich-app# telnet 127.0.0.1 2283
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
root@immich:~/immich-app# telnet 192.168.88.51 2283
Trying 192.168.88.51...
telnet: Unable to connect to remote host: Connection refused
