### ISSUE TITLE
The log shows  Detected new face but in the people shows none

### ISSUE THREAD

**Issue by MuMu360121** [imagegenius/docker-immich#455]
[Nest] 198  - 10/26/2024, 12:28:51 PM     LOG [Microservices:PersonService] Detected 1 new faces in asset a76771ac-ce5b-4362-9efc-6a545f5b085b
![image](https://github.com/user-attachments/assets/bad7ad84-7e46-4ecb-9806-5b410bf6f96c)

the setting like this:

![image](https://github.com/user-attachments/assets/68e8d6cd-5ac8-410b-90b0-4570f424ee14)

the job shows:
![image](https://github.com/user-attachments/assets/f7c00692-49a9-4a80-887d-51ad150ef70a)

what's the problem? Should I wait until the jobs are done?

**Comment by hydazz** [comment]
Believe this may be an upstream issue, please open an issue [there](github.com/immich-app/immich)
