### ISSUE TITLE
Unraid thumbnails broken on 1.119.1, works no issues rollback to 1.118.2

### ISSUE THREAD

**Issue by McGeaverBeaver** [imagegenius/docker-immich#456]
Unraid thumbnails broken on 1.119.1, works no issues rollback to 1.118.2

there is nothing for us to modify. no microservices or ports to adjust.. the jobs do not run... if you go to the jobs page, thumbnails or metadata never run.. go back to 1.118.2 and look at jobs and they are active and running and all new photos loaded thumbnails..

**Comment by tr1ckz** [comment]
Same thing happened to me when I upgraded to 1.119.1, had to rollback to get the jobs to run.

**Comment by hydazz** [comment]
might be fixed with https://github.com/imagegenius/docker-baseimage-immich/pull/10

https://github.com/immich-app/immich/issues/13603

**Comment by McGeaverBeaver** [comment]
same issue with 1.2.0

![image](https://github.com/user-attachments/assets/c12262e8-be9e-4580-a774-c3183a63bcc1)

the issue, is the jobs don't run.. GENERATE THUMBNAILS & EXTRACT METADATA  will just queue.. they will not run. debug has been turned on and there are NO errors other than the thumbnails not being able to be displayed due to them not existing and we know why, Because the job doesn't run..  

why doesn't the job run @hydazz ?

**Comment by hydazz** [comment]
both work for me, I can only assume its an upstream issue.
try open an issue [here](https://github.com/immich-app/immich/issues)

**Comment by McGeaverBeaver** [comment]
not the only one having the issue as you can see..  just because you are not? are you even deployed using unraid?
