### ISSUE TITLE
Ui does not load

### ISSUE THREAD

**Issue by sledgemasterrrr** [imagegenius/docker-immich#459]
Nothing was changed excepted for me restarting it. No therer are no errors in the logs but the webui just will not load anything. 
This is running in docker on Unraid 
[redis.log](https://github.com/user-attachments/files/17625431/redis.log)

**Comment by hydazz** [comment]
the webui container port should be `8080` not `8322`

**Comment by sledgemasterrrr** [comment]
> the webui container port should be `8080` not `8322`

I love you, idk how that got changed that way. Thanks!
