### ISSUE TITLE
Couldn't install latest version

### ISSUE THREAD

**Issue by main1994** [imagegenius/docker-immich#464]
<img width="639" alt="1233333" src="https://github.com/user-attachments/assets/1edab208-8fb9-4733-bad6-a3b23c635d1c">
<img width="968" alt="121212121" src="https://github.com/user-attachments/assets/70f26ce9-663c-42be-8bfe-cb73e997bb93">

**Comment by main1994** [comment]
I clean the database yet

**Comment by martabal** [comment]
Hey :wave: 
Can you give a little more context? Is this a first time install or an upgrade?

> I clean the database yet

What does it mean (did you run some SQL commands)?

**Comment by main1994** [comment]
![1111](https://github.com/user-attachments/assets/2f9db0d4-1395-462b-87ca-d55b6d3aeb71)
![2222222222](https://github.com/user-attachments/assets/d5ca3243-560e-43e5-912f-dcce9b389427)
The previous version worked fine，maybe this version includes an AI module and update failed。so I clean the database and reinstall。

**Comment by martabal** [comment]
No this has nothing to do with AI. My theory is that you shutdown Immich in the middle of a database migration https://github.com/immich-app/immich/blob/main/server/src/migrations/1721249222549-AddSourceColumnToAssetFace.ts

My advice would be to rollback to a previous version of your data se using a backup or delete the `sourceType` row in your database.

**Comment by main1994** [comment]
OK，thank u
