### ISSUE TITLE
Honey, I broke the immich... 

### ISSUE THREAD

**Issue by g8892** [imagegenius/docker-immich#469]
I was following the incredible tutorial by Spaceinvader One when I accidently broke everything.

I executed an API key to log in usuing the command line and typed the following command: **"immich upload --recursive /libraries"**

This recursive command failed according the the logs in the photos. I cannot seem to stop this command, even when removing and reinstalling the docker. 

Can you please help me resolve the error, stop the command, or reinstall the docker to resolve the issue? I'm looking for the most straightforward solution for dummies haha. 

Running latest immich version "1.122.2-cuda"?? on Unraid 6.12.14

![Log with program running](https://github.com/user-attachments/assets/54d6ad46-2cf7-4ccb-b963-a213be4ff77b)
![Log with program stopped](https://github.com/user-attachments/assets/a56f378c-c0e1-4b08-a282-2aae21d8535b)

**Comment by martabal** [comment]
> even when removing and reinstalling the docker

This is an issue with Immich, reinstalling docker won't help

The screen you shared shows a different problem. Immich checks if there's a `.immich` file to know if the folder/disk is correctly mounted which is not the case for you.

**Comment by g8892** [comment]
Thank you so much. I plan to investigate further this weekend.  I appreciate you taking the time to direct my attention to this issue.

**Comment by g8892** [comment]
I have given this the most thorough investigation my skills allow... I cannot find the file path. It seems like I need to force immich to create the file? If there is anything you can think to try I would greatly appreciate it.

**Comment by martabal** [comment]
> I have given this the most thorough investigation my skills allow... I cannot find the file path. It seems like I need to force immich to create the file? If there is anything you can think to try I would greatly appreciate it. 

IIRC, the .immich files are created automatically by Immich to detect if the /photos folder is correctly mounted. You can create it manually if they don't exist.
