### ISSUE TITLE
This site can't be reached when opening Immich

### ISSUE THREAD

**Issue by Stockpro11** [imagegenius/docker-immich#470]
Hi I followed spaceinvader one on how to setup immich the only thing i did different was that the photos were already in a file on the unraid nas i have but when i go to open i get "the site can't be rached" I am a total newbie and I can't figure out what I did wrong, I have chrome checked under the firewall as a good application and I don't see one for immich itself.  Any help would really be appreciated.  Side note this is my first NAS ever

**Comment by martabal** [comment]
Hard to tell without logs, info on your setup, your docker envs...
