### ISSUE TITLE
WebGUI not working

### ISSUE THREAD

**Issue by milan941899** [imagegenius/docker-immich#471]
Hello,

I installed Immich_PostgresSQL and Immich docker how it is shown in the spaceinvaders tutorial on youtube.
But Immich is not working for me.
Here the logs of the immich app:

> `[Nest] 885  - 12/15/2024, 10:57:56 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 192.168.0.202:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)`

here the Immich setup:
![Unbenannt](https://github.com/user-attachments/assets/6a092427-eaeb-4617-bafb-10069296494d)

here the postgres setup:
![Unbenannt1](https://github.com/user-attachments/assets/0cb37ba5-6476-4c86-bb35-39fec7cf4bdc)

What is my error?

Thank you

**Comment by martabal** [comment]
You changed your postgres port to 5433
