### ISSUE TITLE
PostgreSQL_Immich Container on Unraid broken

### ISSUE THREAD

**Issue by natas72716** [imagegenius/docker-immich#473]
Hello, Not sure if anyone else has this issue but I cannot find a resolution. after the most recent update of immich on Unraid, the PostgreSQL_immich container will not run, keep giving the following error in logs. 

![Screenshot 2024-12-21 193259](https://github.com/user-attachments/assets/e23a8d7e-83e8-4f18-9fd8-fa2903a563c2)

**Comment by martabal** [comment]
I don't see any errors in the logs you shared. Closing this issue because it's (probably) an issue with postgres. Please re-open if you think this is an issue with immich.
