### ISSUE TITLE
dont working after installing docker on unraid "connection failed"

### ISSUE THREAD

**Issue by cycycool** [imagegenius/docker-immich#474]
hi 
Immich 
i was tried several time but no succeed "connection failed" so i have right follow the instruction    

I dont understand 

so you can see the screenshot ;)

please 

thanks 
![Unraid_Docke](https://github.com/user-attachments/assets/094bd785-cc3a-45f3-aeee-d8ddcebbd89b)
![Unraid_UpdateContainer1](https://github.com/user-attachments/assets/75a2e62a-f1e1-4b36-adb9-56a0af500ea9)
![Unraid_UpdateContainer](https://github.com/user-attachments/assets/e86f4cd1-479e-41ae-ad3a-5e94f84d6a4b)
![Screenshot 2024-12-22 233107](https://github.com/user-attachments/assets/fe43e6a3-286b-476c-8f1e-cf105d3c1c00)

**Comment by martabal** [comment]
Please share your immich docker logs

**Comment by hydazz** [comment]
You did populate the db hostname...?

**Comment by cycycool** [comment]
> Please share your immich docker logs

╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
chown: cannot access '/usr/src/resources': No such file or directory
/usr/bin/redis-server
**** redis-server already installed, skipping ****
[custom-init] No custom files found, skipping...
Starting api worker
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [NestFactory] Starting Nest application...
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 256  - 12/23/2024, 10:38:11 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND 192.168.1.x
Error: getaddrinfo ENOTFOUND 192.168.1.x
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
api worker exited with code 1

**Comment by cycycool** [comment]
> You did populate the db hostname...?

thanks 
i m big stupid ;) 

it is finally worked 

thank to all
