### ISSUE TITLE
Photos deleted after update

### ISSUE THREAD

**Issue by Medic97** [imagegenius/docker-immich#56]
I updated to the latest version and for some reason all my images were deleted. Even my config which is in a separate folder was wiped. Any ideas what I can do better next time?
On my qnap I just pull the new image and then recreate the app. I didn't change my code at all.

**Comment by martabal** [comment]
Does it affect only Immich ?

**Comment by Medic97** [comment]
only the last 2 updates reset everything. I upgraded previous versions and everything was fine. Also updated my plex and other containers doing the same thing with no problems.

**Comment by martabal** [comment]
Every time you update Immich does it reset all your files?

**Comment by Medic97** [comment]
My last update to v1.52.1-ig74 didn't affect the files or config. I then upgraded to v1.53.0-ig78 and then to v1.53.0-ig79 both times it deleted the config and I came to the first time setup page.

**Comment by martabal** [comment]
Do you use docker-mods ?

**Comment by Medic97** [comment]
Yes both Redis and PostgreSQL

**Comment by martabal** [comment]
I just tried it and I can't reproduce your problem. Can you provide your docker-compose.yml file?

**Comment by Medic97** [comment]
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1004
      - PGID=100
      - TZ=America/New_York
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=********************= 
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres #set Docker mods for both Redis and PostgreSQL
    volumes:
      - /share/CACHEDEV1_DATA/Container/Docker Data/Immich:/Config
      - /share/CACHEDEV3_DATA/NAS Pics/Immich/Photos:/Photos
      - /share/CACHEDEV3_DATA/NAS Pics/Immich/Uploads:/Uploads
    ports:
      - 8080:8080
    network_mode: host
    restart: always

**Comment by martabal** [comment]
It seems there's an error in your docker-compose.yml file.
This should be `/config` and `/photos`, not `/Config` and `/Photos` (capital letters matter).

**Comment by martabal** [comment]
This would explain why you lose your data every time you restart docker

**Comment by Medic97** [comment]
Ok fixed that, you think that could have caused the issue. It would have been there for the last few updates before this one that wiped everything.

**Comment by martabal** [comment]
You haven't changed your docker-compose between v1.52.1-ig74 and v1.53.0-ig78?

**Comment by Medic97** [comment]
no. I did the update last night without changing anything.

**Comment by hydazz** [comment]
Is there anything in `/share/CACHEDEV3_DATA/NAS Pics/Immich/Photos`?

**Comment by martabal** [comment]
That's weird. With your current docker-compose.yml you should have had this problem before.

**Comment by Medic97** [comment]
I'll just wipe all the folders and start again. Hopefully for the last time. I had just finished uploading and machine learning for 53k photos late last week.

**Comment by hydazz** [comment]
> I'll just wipe all the folders and start again. Hopefully for the last time. I had just finished uploading and machine learning for 53k photos late last week.

Upload like 1 photo, recreate the container and make sure that the data persists

**Comment by Medic97** [comment]
Unrelated but installing the new update from scratch and my log is full of this error. 
<img width="668" alt="Screenshot 2023-04-10 at 5 48 28 PM" src="https://user-images.githubusercontent.com/23649478/231005622-078aedac-7f54-48ad-a146-4ca7edec4490.png">

**Comment by hydazz** [comment]
Update the container - should be fixed
