### ISSUE TITLE
multiple errors when uploading photos

### ISSUE THREAD

**Issue by viriatusX** [imagegenius/docker-immich#57]
Hi,
I have installed your latest version of Immich on my Unraid server. My CPU supports AVX, but every time I upload an image, the log shows these errors.
The picture uploads correctly to Immich but those errors.....
Any idea what can cause those errors?

Thanks.

<img width="1197" alt="Captura de pantalla 2023-04-10 a las 15 20 24" src="https://user-images.githubusercontent.com/64467637/230908959-d209aefe-951b-461e-9141-4ec06b100db4.png">

**Comment by hydazz** [comment]
Is there anything in `/config/transformers`?

**Comment by martabal** [comment]
With the logs you provided, It seems your machine learning is not running. Can you provide all logs ?

**Comment by viriatusX** [comment]
> Is there anything in `/config/transformers`?

I have 1 file with "version.txt"

**Comment by viriatusX** [comment]
> With the logs you provided, It seems your machine learning is not running. Can you provide all logs ?

MachineLearning seems to be enabled. But every time I upload a picture, it shows the same errors.

<img width="1312" alt="Captura de pantalla 2023-04-10 a las 15 48 49" src="https://user-images.githubusercontent.com/64467637/230913898-50bc4feb-0593-44ca-860c-ea2555add14f.png">
<img width="1312" alt="Captura de pantalla 2023-04-10 a las 15 48 44" src="https://user-images.githubusercontent.com/64467637/230913900-2f8d050c-6a22-46ac-a21e-2be87d4b0864.png">
<img width="1312" alt="Captura de pantalla 2023-04-10 a las 15 48 38" src="https://user-images.githubusercontent.com/64467637/230913902-7262b5b0-438d-465d-9d2d-f0a302216fb3.png">

**Comment by hydazz** [comment]
@viriatusX open a console into the container, make a new file called install.py with the contents:

```python
from transformers import pipeline
from sentence_transformers import SentenceTransformer

# This script installs the models in the TRANSFORMERS_CACHE folder

classification_model = pipeline(task="image-classification", model="microsoft/resnet-50")
object_model = pipeline(task="object-detection", model="hustvl/yolos-tiny")
clip_model = SentenceTransformer("clip-ViT-B-32")
```

Run the script: `python3 install.py` (it will spit out errors)

Have a look in the `/config/transformers` folder, are there now other folders in it?

**Comment by grokuku** [comment]
I had exactly the same issue on unraid, running this python script seems to do the trick.
I now have those folders inside the transformers directory:
models--hustvl--yolos-tiny/  
models--microsoft--resnet-50/  
sentence-transformers_clip-ViT-B-32/

**Comment by viriatusX** [comment]
Hi,
<img width="1312" alt="Captura de pantalla 2023-04-10 a las 18 10 02" src="https://user-images.githubusercontent.com/64467637/230943120-069e31fe-99a1-4260-b3bf-d5445f8df935.png">
<img width="1305" alt="Captura de pantalla 2023-04-10 a las 18 09 11" src="https://user-images.githubusercontent.com/64467637/230943126-b069eb6a-5848-4a87-9003-0cd154ad6c97.png">
<img width="1312" alt="Captura de pantalla 2023-04-10 a las 18 10 06" src="https://user-images.githubusercontent.com/64467637/230943113-55a45274-296a-4d91-b462-9849c674d10c.png">

<img width="1312" alt="Captura de pantalla 2023-04-10 a las 18 10 09" src="https://user-images.githubusercontent.com/64467637/230943099-60c97e74-8221-402e-a35c-6633f27093bb.png">

**Comment by martabal** [comment]
Can you run `ps aux` inside your Immich container and print here the output ?

**Comment by martabal** [comment]
@hydazz It seems gunicorn prevents to download the models

**Comment by viriatusX** [comment]
Is there anything I can do? Or wait for it to be fixed? Thanks

**Comment by martabal** [comment]
Can you try with v1.53.0-ig79 ?

**Comment by viriatusX** [comment]
> Can you try with v1.53.0-ig79 ?

With the ghcr.io/imagegenius/immich:v1.53.0-ig79 errors are reduced to 1:

<img width="1312" alt="Captura de pantalla 2023-04-10 a las 20 44 02" src="https://user-images.githubusercontent.com/64467637/230970923-46371621-f74e-40c5-b247-8f0425fd5450.png">
<img width="1312" alt="Captura de pantalla 2023-04-10 a las 20 43 58" src="https://user-images.githubusercontent.com/64467637/230970948-348d0df3-7865-41ee-9b40-7c6061498574.png">

**Comment by martabal** [comment]
What fs do you use on Unraid ?

**Comment by viriatusX** [comment]
> What fs do you use on Unraid ?

I have all the dockers in a pool with BTRFS format.

**Comment by viriatusX** [comment]
Update: This happens because the main array does not support symlinks. It is solved by moving the "images" folder to a pool outside the array.

**Comment by martabal** [comment]
Great !

**Comment by hydazz** [comment]
> Update: This happens because the main array does not support symlinks. It is solved by moving the "images" folder to a pool outside the array.

By default the array should support symlinks. What happens when you manually use ln to create one on the array?

**Comment by hydazz** [comment]
@viriatusX try updating the container and see if the errors change

**Comment by viriatusX** [comment]
> @viriatusX try updating the container and see if the errors change

The error of my last message persists. Only when I indicate that the photos are saved on a HDD of the main array. (/mnt/user/immich) if I indicate the docker with the folder photos in a pool, there is no error (mnt/download/immich) It is strange. 
Something happens with symlinks in the main array. I had problems with a postgressql DB in the past because of something like this. What happens if I leave immich in the main array without symlinks "working"? Is it something mandatory for immich?

**Comment by hydazz** [comment]
oopsie

**Comment by hydazz** [comment]
the error does not explicitly state `symlink` rather `link`, I too have the `/photos` folder mounted on the array and these errors are not happening. try run a storage migration and look in the `/photos/upload` folder. how many items are in it?

**Comment by viriatusX** [comment]
> the error does not explicitly state `symlink` rather `link`, I too have the `/photos` folder mounted on the array and these errors are not happening. try run a storage migration and look in the `/photos/upload` folder. how many items are in it?

It is very strange. If I save the photos in "/mnt/user/immich" the error appears, but if I select "mnt/disk1/immich" (disk 1 of the main array), the error disappears. I'll leave it like this so that it doesn't give problems... If it doesn't happen to you, it must be something strange in my configuration. My file system is xfs.

**Comment by hydazz** [comment]
I have a feeling that when your uploading a photo and it goes in the `upload/upload` folder (within the container), and it may or may not be going into say `disk1` on unraid, but when immich tries to move/hardlink (I think its hardlinking) to `/uploads/library`, unraid tries to put that hardlink on another disk, say `disk2` which hardlinks cant do across disks. Which is the only explanation for why setting it to `mnt/disk1/immich` works
