### ISSUE TITLE
Cannot connect to DB

### ISSUE THREAD

**Issue by joshoram80** [imagegenius/docker-immich#69]
I have an existing Postgres container that I use for 5 other services and it works fine. For some reason I can't get immich to use the role 'immich' I have created for it to access the database 'immich'. The database is owned by that 'immich' user and they have full privileges for that DB.

```
ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: function uuid_generate_v4() does not exist
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CreateUserTable1645130759468.up (/app/immich/server/dist/apps/immich/libs/infra/src/migrations/1645130759468-CreateUserTable.js:6:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:223:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:256:35)
    at async DataSource.initialize (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:144:17)
```

The only way I can get it to work is to use a superuser account to access the database which is obviously not ideal.

**Comment by hydazz** [comment]
What postgres version is it?

**Comment by igormsiqueira** [comment]
Hi, I have the same issue postgres 14,

**Comment by martabal** [comment]
Did you grant correct permissions to your database ?

**Comment by igormsiqueira** [comment]
Hey! I only followed the installation steps with docker and got the issue, since posting this comment I nuked everything and installed portainer and re-did my installation and same result. Could you instruct me on how to grant the permissions you mentioned?

Thanks

**Comment by martabal** [comment]
For postgres 14 : `GRANT ALL PRIVILEGES ON DATABASE <db> TO <user>;`

**Comment by igormsiqueira** [comment]
Hi!
I've executed `docker exec -it immich_postgres psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE immich TO postgres"` on a clean install after pruning all volumes and starting fresh, the command output's `GRANT` and the database logs do show `database system is ready to accept connections` but the problem persists, I don't know whats up

**Comment by joshoram80** [comment]
Check the ownership of the schema as well. Mine had a different owner to
the database somehow and that caused my issue

**Comment by martabal** [comment]
>`database system is ready to accept connections` 

don't mean you have the correct permissions for your users, it just means the db is up and running

**Comment by martabal** [comment]
@igormsiqueira when executing the command it should print `GRANT`

**Comment by igormsiqueira** [comment]
Hey everyone, tried the above suggestions - I do see a `GRANT` print when I run the permission command and a `ALTER DATABASE` when changing the permissions I also noticed that the log's print `The files belonging to this database system will be owned by user "postgres"` I would also show my actual user when I tried without the default values from the github sample, 

I also tried the installation from [portainer ](https://immich.app/docs/install/portainer) directly, same results.

In the server logs I see:
Error: connect EHOSTUNREACH IP:5432 
right after the can't connect error where this IP is the database IP so now I'm thinking is something related to the network maybe?

Thanks fo your help

**Comment by martabal** [comment]
Yep sounds like a network issue

**Comment by hydazz** [comment]
> I still have issues with this and Postgres 12 (I am only using 12 as Authentik still has issues with 14\15). I can only get Immich to connect to the DB if I use a superuser account which is not ideal

have to tried it with postgres 14? postgres 12 is not really supported

**Comment by wodepig** [comment]
uuid_ generate_ V4() should be a module that needs to be installed separately, but I won't install it, gen_ random_ Uuid() is the default supported uuid generation after PG13, perhaps just modify the table creation statement
> uuid_generate_v4()应该是个模块需要单独安装,但是我不会安装,gen_random_uuid()是pg13以后默认支持的uuid生成,也许把建表语句改一下就行了

**Comment by maxistviews** [comment]
Sorry to dregde up an old post - but if someone is like me and was using Postgres 11 to try to set this up.... get Postgres15, worked like a charm.

Commands used:

```
psql -d postgres -U postgres
CREATE DATABASE immich;
GRANT ALL PRIVILEGES ON DATABASE immich TO postgres;
```

**Comment by hydazz** [comment]
Issues appear resolved 😸
