### ISSUE TITLE
UNRAID - SWAG reverse proxy help needed

### ISSUE THREAD

**Issue by guim31** [imagegenius/docker-immich#71]
Hi, 

I'm sorry for this issue title, I don't know how to explain my issue ^^
I try to setup Immich on my Unraid server to be reachable from a url like this : immich.mydomain.ovh (like every other *arr apps I run)

But I don't know how to edit my proxy conf file in order to make it work. I always get a 502 error :/ 

Here is my proxy conf file : 

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name immich.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app immich;
        set $upstream_port 8282;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

Anyone to help me with this ?

**Comment by guim31** [comment]
I don't know how I should do it.
I launched the console like this : 
![image](https://user-images.githubusercontent.com/33096540/235905836-cca8ea22-4ee0-45fa-9776-0255e09fc31a.png)

And paste `curl http://immich:8282/auth/login` to get this result : 
`curl: (7) Failed to connect to immich port 8282 after 1 ms: Connection refused`

**Comment by guim31** [comment]
BUT if I do this (with my local IP adress) : 
`curl http://192.168.100.150:8282/auth/login`

It returns this : 
`<!DOCTYPE html>
<html lang="en" class="dark">
        <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link href="../_app/immutable/assets/_layout.1b9669ee.css" rel="stylesheet"><title>Login - Immich</title><link rel="icon" href="/_app/immutable/assets/favicon.24f3c859.png"><meta name="description">


                <meta property="og:type" content="website">
                <meta property="og:title" content="Login">
                <meta property="og:description">
                <meta property="og:image">


                <meta name="twitter:card" content="summary_large_image">
                <meta name="twitter:title" content="Login">
                <meta name="twitter:description">
                <meta name="twitter:image">
                <script>
                        /**
                         * Prevent FOUC on page load.
                         */
                        const theme = localStorage.getItem('color-theme') || 'dark';
                        if (theme === 'light') {
                                document.documentElement.classList.remove('dark');
                        }
                </script>
        </head>

        <body class="bg-immich-bg dark:bg-immich-dark-bg">
                <div>




<noscript class="h-screen w-screen absolute z-[1000] flex place-items-center place-content-center bg-immich-bg dark:bg-immich-dark-bg dark:text-immich-dark-fg"><section class="min-h-screen w-screen flex place-items-center place-content-center p-4"><div class="flex flex-col gap-4 border bg-white dark:bg-immich-dark-gray dark:border-immich-dark-gray p-8 shadow-sm w-full max-w-lg rounded-3xl"><div class="flex flex-col place-items-center place-content-center gap-4 py-4"><img src="/_app/immutable/assets/immich-logo.18dcdcef.svg" alt="Immich Logo" draggable="false" class="h-24 w-24">
                        <h1 class="text-2xl text-immich-primary dark:text-immich-dark-primary font-medium">Welcome to Immich</h1></div>



                To use Immich, you must enable JavaScript or use a JavaScript compatible browser.
        </div></section></noscript>



<section class="min-h-screen w-screen flex place-items-center place-content-center p-4"><div class="flex flex-col gap-4 border bg-white dark:bg-immich-dark-gray dark:border-immich-dark-gray p-8 shadow-sm w-full max-w-lg rounded-3xl"><div class="flex flex-col place-items-center place-content-center gap-4 py-4"><img src="/_app/immutable/assets/immich-logo.18dcdcef.svg" alt="Immich Logo" draggable="false" class="h-24 w-24">
                        <h1 class="text-2xl text-immich-primary dark:text-immich-dark-primary font-medium">Login</h1></div>



                <form class="flex flex-col gap-5 mt-5">

                <div class="flex flex-col gap-2"><label class="immich-form-label" for="email">Email</label>
                        <input class="immich-form-input" id="email" name="email" type="email" autocomplete="email" required value=""></div>

                <div class="flex flex-col gap-2"><label class="immich-form-label" for="password">Password</label>
                        <input class="immich-form-input" id="password" name="password" type="password" autocomplete="current-password" required value=""></div>

                <div class="my-5 flex w-full"><button type="submit" disabled title="" class="inline-flex justify-center items-center transition-colors disabled:cursor-not-allowed disabled:opacity-60 bg-immich-primary dark:bg-immich-dark-primary text-white dark:text-immich-dark-gray enabled:dark:hover:bg-immich-dark-primary/80 enabled:hover:bg-immich-primary/90 px-6 py-4 font-semibold  rounded-3xl  shadow-md w-full">Login</button></div></form>



</div></section>











                        <script>
                                {
                                        __sveltekit_1xlvujc = {
                                                env: {"PUBLIC_IMMICH_SERVER_URL":"http://127.0.0.1:3001"},
                                                base: new URL("..", location).pathname.slice(0, -1),
                                                element: document.currentScript.parentElement
                                        };

                                        const data = [{"type":"data","data":{serverVersion:{major:1,minor:54,patch:1},user:void 0},"uses":{}},{"type":"data","data":{authConfig:{enabled:false,passwordLoginEnabled:true,url:void 0},meta:{title:"Login"}},"uses":{}}];

                                        Promise.all([
                                                import("../_app/immutable/entry/start.dcc2682d.js"),
                                                import("../_app/immutable/entry/app.34956c31.js")
                                        ]).then(([kit, app]) => {
                                                kit.start(app, __sveltekit_1xlvujc.element, {
                                                        node_ids: [0, 26],
                                                        data,
                                                        form: null,
                                                        error: null
                                                });
                                        });
                                }
                        </script>
                </div>
        </body>
</html>`

**Comment by martabal** [comment]
> I don't know how I should do it. I launched the console like this : ![image](https://user-images.githubusercontent.com/33096540/235905836-cca8ea22-4ee0-45fa-9776-0255e09fc31a.png)
> 
> And paste `curl http://immich:8282/auth/login` to get this result : `curl: (7) Failed to connect to immich port 8282 after 1 ms: Connection refused`

Not from your Immich container, from your swag container. I want to make sure Immich and swag can communicate together.

**Comment by guim31** [comment]
My bad... sorry

```root@NASDOURY:~# docker exec -it swag  bash

root@1113b321ddaf:/# curl http://immich:8282/auth/login

curl: (7) Failed to connect to immich port 8282: Connection refused```

**Comment by guim31** [comment]
Yes, the result is the same HTML page

**Comment by martabal** [comment]
I mean for the `curl`command inside your swag container : `docker exec -it swag curl http://<immich_ip_address>:8282/auth/login`.

**Comment by guim31** [comment]
```
root@NASDOURY:~# docker exec -it swag curl http://192.168.100.150:8282/auth/login
<!DOCTYPE html>
<html lang="en" class="dark">
        <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link href="../_app/immutable/assets/_layout.1b9669ee.css" rel="stylesheet"><title>Login - Immich</title><!-- HEAD_svelte-vaya7v_START --><link rel="icon" href="/_app/immutable/assets/favicon.24f3c859.png"><meta name="description">


                <meta property="og:type" content="website">
                <meta property="og:title" content="Login">
                <meta property="og:description">
                <meta property="og:image">


                <meta name="twitter:card" content="summary_large_image">
                <meta name="twitter:title" content="Login">
                <meta name="twitter:description">
                <meta name="twitter:image"><!-- HEAD_svelte-vaya7v_END -->
                <script>
                        /**
                         * Prevent FOUC on page load.
                         */
                        const theme = localStorage.getItem('color-theme') || 'dark';
                        if (theme === 'light') {
                                document.documentElement.classList.remove('dark');
                        }
                </script>
        </head>

        <body class="bg-immich-bg dark:bg-immich-dark-bg">
                <div>




<noscript class="h-screen w-screen absolute z-[1000] flex place-items-center place-content-center bg-immich-bg dark:bg-immich-dark-bg dark:text-immich-dark-fg"><section class="min-h-screen w-screen flex place-items-center place-content-center p-4"><div class="flex flex-col gap-4 border bg-white dark:bg-immich-dark-gray dark:border-immich-dark-gray p-8 shadow-sm w-full max-w-lg rounded-3xl"><div class="flex flex-col place-items-center place-content-center gap-4 py-4"><img src="/_app/immutable/assets/immich-logo.18dcdcef.svg" alt="Immich Logo" draggable="false" class="h-24 w-24">
                        <h1 class="text-2xl text-immich-primary dark:text-immich-dark-primary font-medium">Welcome to Immich</h1></div>



                To use Immich, you must enable JavaScript or use a JavaScript compatible browser.
        </div></section></noscript>



<section class="min-h-screen w-screen flex place-items-center place-content-center p-4"><div class="flex flex-col gap-4 border bg-white dark:bg-immich-dark-gray dark:border-immich-dark-gray p-8 shadow-sm w-full max-w-lg rounded-3xl"><div class="flex flex-col place-items-center place-content-center gap-4 py-4"><img src="/_app/immutable/assets/immich-logo.18dcdcef.svg" alt="Immich Logo" draggable="false" class="h-24 w-24">
                        <h1 class="text-2xl text-immich-primary dark:text-immich-dark-primary font-medium">Login</h1></div>



                <form class="flex flex-col gap-5 mt-5">

                <div class="flex flex-col gap-2"><label class="immich-form-label" for="email">Email</label>
                        <input class="immich-form-input" id="email" name="email" type="email" autocomplete="email" required value=""></div>

                <div class="flex flex-col gap-2"><label class="immich-form-label" for="password">Password</label>
                        <input class="immich-form-input" id="password" name="password" type="password" autocomplete="current-password" required value=""></div>

                <div class="my-5 flex w-full"><button type="submit" disabled title="" class="inline-flex justify-center items-center transition-colors disabled:cursor-not-allowed disabled:opacity-60 bg-immich-primary dark:bg-immich-dark-primary text-white dark:text-immich-dark-gray enabled:dark:hover:bg-immich-dark-primary/80 enabled:hover:bg-immich-primary/90 px-6 py-4 font-semibold  rounded-3xl  shadow-md w-full">Login</button></div></form>



</div></section>











                        <script>
                                {
                                        __sveltekit_1xlvujc = {
                                                env: {"PUBLIC_IMMICH_SERVER_URL":"http://127.0.0.1:3001"},
                                                base: new URL("..", location).pathname.slice(0, -1),
                                                element: document.currentScript.parentElement
                                        };

                                        const data = [{"type":"data","data":{serverVersion:{major:1,minor:54,patch:1},user:void 0},"uses":{}},{"type":"data","data":{authConfig:{enabled:false,passwordLoginEnabled:true,url:void 0},meta:{title:"Login"}},"uses":{}}];

                                        Promise.all([
                                                import("../_app/immutable/entry/start.dcc2682d.js"),
                                                import("../_app/immutable/entry/app.34956c31.js")
                                        ]).then(([kit, app]) => {
                                                kit.start(app, __sveltekit_1xlvujc.element, {
                                                        node_ids: [0, 26],
                                                        data,
                                                        form: null,
                                                        error: null
                                                });
                                        });
                                }
                        </script>
                </div>
        </body>
</html>
```

**Comment by martabal** [comment]
> Yes, the result is the same HTML page

You replaced `set $upstream_app immich;` with immich ip address ?

**Comment by guim31** [comment]
IT WORKS !!! Thanks a lot !!

**Comment by martabal** [comment]
Great !

**Comment by guim31** [comment]
Yeah this is what I thought but I don't have the skills to debug it.
Thanks a lot and let me say that Immich is fantastic :)
I just wait for the ability to use an existing library to use it 100% !!

**Comment by martabal** [comment]
Ahah yeah, it really is. You are not the only one waiting for this feature :).
