### ISSUE TITLE
Tags for the pre-release

### ISSUE THREAD

**Issue by DrSpaldo** [imagegenius/docker-immich#85]
Hi, I would like to update to the new 1.56.2 however it isn't pulling on the normal "latest" tag as it appears to be listed as a pre-release. What would I change to get the latest release regardless of pre-release? I currently use the following in Unraid ghcr.io/imagegenius/immich:latest

**Comment by martabal** [comment]
Hello, the noml image is built faster than the normal image. Normal and noml versions are released 0-2 hours after the official Immich release if there's no breaking changes.

**Comment by DrSpaldo** [comment]
Ah ok, sorry, I must have been too impatient :)
