### ISSUE TITLE
Limit CPU option

### ISSUE THREAD

**Issue by DrSpaldo** [imagegenius/docker-immich#87]
Any chance that the limit CPU could be an option in the Unraid config?

https://github.com/immich-app/immich/discussions/2368#discussioncomment-5952765

**Comment by hydazz** [comment]
You can enable CPU pinning on unraid by going to the template, enabling advanced view and pinning the container to certain cores

![image](https://github.com/imagegenius/docker-immich/assets/53986978/a730d3be-a8e2-4765-ba29-50655d33952e)

**Comment by DrSpaldo** [comment]
> You can enable CPU pinning on unraid by going to the template, enabling advanced view and pinning the container to certain cores
> 
> ![image](https://user-images.githubusercontent.com/53986978/239715281-a730d3be-a8e2-4765-ba29-50655d33952e.png)

Yep, thanks @hydazz , I’ve done that. I was just wanted to see what difference those options make as the processing currently maxes out all the allocated CPU’s

**Comment by hydazz** [comment]
Setting resources in docker compose vs cpu pinning in unraid?

**Comment by DrSpaldo** [comment]
> Setting resources in docker compose vs cpu pinning in unraid?

Correct. I wasn't sure if there was a difference though, because in the compose setting, you are limiting say the machine learning container and still giving the other containers some CPU time. When you do the whole Unraid app pinning, then it would limit the lot and if the learning was hogging it all up there would be none left over. I am probably over thinking too much...

**Comment by hydazz** [comment]
it is possible to achieve what you are looking for by starting the services with `taskset`, which allows you to virtually set what cores that process is allowed to use, but this isnt particularly a priority, though is possible to add
