### ISSUE TITLE
Dropping support for the PostgreSQL docker mod

### ISSUE THREAD

**Issue by hydazz** [imagegenius/docker-immich#90]
Soon this image will be rebased to ubuntu 23.04 so we can install the latest packages, as a side effect, the docker mod used up to this point will no longer work, as postgres 14 is not available in 23.04, however postgres 15 is available on 23.04, so if you're really keen on using the docker mod you can set `PG_VERSION` (enviroment variable) to `15`.

 **This will not work if you already have a postgres 14 instance, you will need to manually migrate postgres14>15, do not just set this variable if you are already using the mod!**

We recommend that you migrate the docker mod's postgres data to a seperate container...

1. Stop the Immich container.

   - If you're using Unraid:
     - Open the Unraid terminal.
     - Execute: `cp -R /mnt/user/appdata/immich/postgres /mnt/user/appdata/postgresql14`

   - For other systems:
     - Open your terminal.
     - Run: `mv <path_to_immich>/postgres <somewhere_else>/postgresql14`

2. Start the Postgres 14 container.

   - On Unraid:
     - Open the Community Applications (CA) and search for "postgresql14".
     - Remove all variables (password, user and database), these are for new installs, and as we are coping over the postgres data, these variables are not applicable.
     - Verify that the Database Storage Path is set to "/mnt/user/appdata/postgres14".
     - Start the container and check the logs. You should see "database system is ready to accept connections".

   - For other systems:
     - Use the provided Docker Compose file [here](https://github.com/imagegenius/docker-immich#docker-compose).
     - Make sure to adjust the necessary configurations according to your setup.

3. Update Immich variables.

   - Modify the `DB_HOSTNAME` value in your template/docker-compose to match the IP address of your Postgres server (the IP of the system if both containers are on the same machine).
   - Confirm that both the Postgres and Immich containers are set to the same network mode, eg. `bridge`.

If any of these steps encounter issues, please do not proceed and kindly provide us with more information about the problem you encountered.

Don't forget to remove "imagegenius/mods:universal-postgres" from your `DOCKER_MODS` variable.

again, apologies for the inconvenience, if you're really pressed you can pull `ghcr.io/imagegenius/immich:v1.57.1-ig105`, which is the last build with the old base image that supports postgres 14.

**If you are getting connection errors look here: https://github.com/imagegenius/docker-immich/issues/90#issuecomment-1562044094, check if postgres is listening on `0.0.0.0`

**Comment by niyazaki** [comment]
Hello, I just did the migration and the app is working fine but it seems to treat me as a new user. So I re-registred myself and now I lost all my pictures.

I'm on unraid, the only difference I made was in the mv command : mv /mnt/user/appdata/immich/postgres /mnt/cache_nvme/appdata/postgresql14
As I had set the storage path of postgresql14 to a cache drive directly. Do you think this may be the cause ? As for me, the app should not be able to tell the difference (regarding the way unraid works with those directory).

**Comment by hydazz** [comment]
Can you provide an `ls /mnt/cache_nvme/appdata/postgresql14`

**Comment by martabal** [comment]
Make sure `Database Storage Path` is set to  `/mnt/cache_nvme/appdata/postgresql14` in your Postgres template

**Comment by langerdennis** [comment]
Hi, unfortunately this is not working for me. I had set DB name, user and PW to "postgres" in the variables for the Postgres container (just like in the immich template), but the immich container is refusing to connect to the database.

`[Nest] 579 05/24/2023, 12:06:03 PM ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: Connection terminated unexpectedly
at Connection. <anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Socket. <anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:62:12)
at Socket.emit (node:events:513:28)
at TCP. <anonymous> (node:net: 322:12)`

**Comment by hydazz** [comment]
The variables in the new postgres container dont do anything as the database, if copied over correctly would have already been initialised...
@martabal

**Comment by Hukuma1** [comment]
What's the proper way of going back to an older version where it still behaved normally? I definitely was affected out of nowhere due to using Watchtower... :(

**Comment by hydazz** [comment]
@Hukuma1 What do you use to start the container? docker compose, unraid template?...

**Comment by hydazz** [comment]
@DrSpaldo 
check the postgres container logs, make sure its started, also within the immich container run `nc -v -z <postgres ip> <postges port>`, you should see something like 
`Connection to 192.168.1.2 port 5432 [tcp/pcsync-https] succeeded!`, or you will see nothing, if the containers cant communicate

**Comment by DrSpaldo** [comment]
Thanks @hydazz the postgres log is:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-05-24 21:28:26.715 AEST [1] LOG: starting PostgreSQL 14.8 (Debian 14.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-05-24 21:28:26.722 AEST [1] LOG: listening on IPv4 address "127.0.0.1", port 5432
2023-05-24 21:28:26.722 AEST [1] LOG: could not bind IPv6 address "::1": Cannot assign requested address
2023-05-24 21:28:26.808 AEST [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-05-24 21:28:26.815 AEST [27] LOG: database system was shut down at 2023-05-24 21:21:02 AEST
2023-05-24 21:28:26.819 AEST [1] LOG: database system is ready to accept connections
```
I will start up immich now and try that command

**Comment by hydazz** [comment]
@DrSpaldo ah! pesky postgres, its listening on `listening on IPv4 address "127.0.0.1", port 5432`, which wont allow for external connections, stop the container, you need to edit `postgresql.conf` in the appdata, and set `listen_addresses` to `*` (`listen_addresses = '*'`) start, and check if `listening on IPv4 address "127.0.0.1", port 5432` changes to `listening on IPv4 address "0.0.0.0", port 5432`

**Comment by DrSpaldo** [comment]
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-05-25 09:26:36.850 AEST [1] LOG: starting PostgreSQL 14.8 (Debian 14.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-05-25 09:26:36.857 AEST [1] LOG: listening on IPv4 address "0.0.0.0", port 5432
2023-05-25 09:26:36.857 AEST [1] LOG: listening on IPv6 address "::", port 5432
2023-05-25 09:26:36.983 AEST [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-05-25 09:26:37.006 AEST [27] LOG: database system was shut down at 2023-05-25 09:23:36 AEST
2023-05-25 09:26:37.013 AEST [1] LOG: database system is ready to accept connections
2023-05-25 09:26:37.613 AEST [34] FATAL: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "postgres", no encryption
2023-05-25 09:26:40.616 AEST [35] FATAL: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "postgres", no encryption
2023-05-25 09:26:43.620 AEST [36] FATAL: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "postgres", no encryption
```

**Comment by hydazz** [comment]
backup `pg_hba.conf`, then edit the original, change the bottom bit to:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

host all all all scram-sha-256
```

**Comment by DrSpaldo** [comment]
Looks like it might be working

**Comment by hydazz** [comment]
> Looks like it might be working 

Success?

**Comment by DrSpaldo** [comment]
> Success?

So far, so good :)

**Comment by Hukuma1** [comment]
> @Hukuma1 What do you use to start the container? docker compose, unraid template?...

Sorry, Docker Compose in my case!

`image: ghcr.io/imagegenius/immich:latest`

Is it safe to put in an older version? Or did some migration stuff happen?

**Comment by hydazz** [comment]
it is safe to change it to `ghcr.io/imagegenius/immich:v1.57.1-ig105`, which is the latest version for which the docker mod will work, but we would recommend moving to a seperate postgres container, you would obviously not get any future updates pinning the version. Is there a reason you really want to stick with the docker mod?

**Comment by Hukuma1** [comment]
The reason is the original reason I chose this image was to have an all-in-one Docker container solution. Only reason for the roll back right now is because I'm scared to lose anything and would want to back up the photos in case the newer version migration to external postgres won't work.

**Comment by langerdennis** [comment]
Working for me too now, listening address was the problem. Thanks for the quick support!

**Comment by ollioddi** [comment]
Hey. I am running on Unraid and have successfully migrated the database to a separate container. However, Immich still thinks that i am running the docker mod, but the variable does not contain it anymore.
![image](https://github.com/imagegenius/docker-immich/assets/7466744/565c5671-9a19-41f7-832c-2667b24fc66d)

Am i missing something obvious? Logs:

> 2023-05-26T16:25:06.388261415Z [mod-init] Attempting to run Docker Modification Logic
2023-05-26T16:25:06.524899085Z [mod-init] Adding imagegenius/mods:universal-redis to container
2023-05-26T16:25:07.751438433Z [mod-init] imagegenius/mods:universal-redis at sha256:d79cc7c55bbb144e66370494abc938bc3ec42361fa3ac829f8eca48a9d7b1d43 has been previously applied skipping
2023-05-26T16:25:07.782135465Z [migrations] started
2023-05-26T16:25:07.782155400Z [migrations] no migrations found
2023-05-26T16:25:07.807322868Z 
2023-05-26T16:25:07.807336247Z ╔═══════════════════════════════╗
2023-05-26T16:25:07.807353054Z   Baseimage from linuxserver.io
2023-05-26T16:25:07.807953878Z ╠═══════════════════════════════╣
2023-05-26T16:25:07.807968988Z   To support this applications developer(s) visit:
2023-05-26T16:25:07.807973497Z   Immich: https://immich.app/docs/overview/support-the-project
2023-05-26T16:25:07.809230854Z ╠═══════════════════════════════╣
2023-05-26T16:25:07.809242988Z   User/Group ID:
2023-05-26T16:25:07.809245523Z   User UID: 99
2023-05-26T16:25:07.809247493Z   User GID: 100
2023-05-26T16:25:07.809249506Z ╚═══════════════════════════════╝
2023-05-26T16:25:07.818905513Z Hey there!
2023-05-26T16:25:07.818928041Z It looks like you're using the PostgreSQL docker mod, unfortunately this mod is no longer supported as there are no longer PostgreSQL 14 upstream packages, there is nothing we can do about this :(.
2023-05-26T16:25:07.818933380Z We recommend migrating the docker mod to a dedicatied PostgreSQL container, this is easier than it sounds, please see the github issue below for some steps, and if you need a lil' extra help, just reply and well help out out ASAP!
2023-05-26T16:25:07.818938809Z https://github.com/imagegenius/docker-immich/issues/90

**Comment by hydazz** [comment]
> Somehow the "posgres" folder was not deleted while moving the files

the folder was `cp`ed? so it possible was not moved

**Comment by alexbelgium** [comment]
Hi, I've developed an homeassistant add-on allowing to run immich on their HAos system. Globally the add-on is a shell around your container.

My main issue is that add-ons on homeassistant (HA) should be self contained (which is why you container is great), and that there is no add-on for postgresql that would allow to self host it on HA.

As such, to keep users experience continuity I was interested in your option described `so if you're really keen on using the docker mod you can set PG_VERSION (enviroment variable) to 15` : is there any downside? Or else it just allows to continue having a fully omni system?

Thanks

**Comment by martabal** [comment]
Hello ! We moved away from Ubuntu LTS (22.04) to latest Ubuntu interim versions (23.04 when this message is written) so we can have latest packages versions, but Postgres does not provide arm64 binaries for non-LTS versions. Another problem, not an issue but a big difficulty, is that Postgres does not provide an automatic migration mechanism to update from one major version to another and this mechanism requires binaries from the previous Postgres version and the actual Postgres version.

**Comment by hydazz** [comment]
> Hi, I've developed an [homeassistant add-on](https://github.com/alexbelgium/hassio-addons/tree/master/immich) allowing to run immich on their HAos system. Globally the add-on is a shell around your container.
> 
> My main issue is that add-ons on homeassistant (HA) should be self contained (which is why you container is great), and that there is no add-on for postgresql that would allow to self host it on HA.
> 
> As such, to keep users experience continuity I was interested in your option described `so if you're really keen on using the docker mod you can set PG_VERSION (enviroment variable) to 15` : is there any downside? Or else it just allows to continue having a fully omni system?
> 
> Thanks

the `PG_VERSION` variable just tells the docker mod what version of postgres to install, by default its 14, and as @martabal said above pg14 is no longer available, so you will need to manage to update the postgres14 database to postgres15 to continue using postgres inside the container. 

If you can find a way to get postgres14 AND 15 installed at the same time you can use something like this:
```bash
#!/bin/bash

export PATH=$PATH:/usr/lib/postgresql/15/bin/

echo "deb http://apt.postgresql.org/pub/repos/apt/ lunar-pgdg main" >/etc/apt/sources.list.d/pgdg.list
curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null

apt update
apt-get install -y \
	postgresql-14 \
	postgresql-15

mv /config/postgres /config/postgres.old
mkdir /config/postgres

chown -R postgres:postgres \
	/config/postgres \
	/config/postgres.old

s6-setuidgid postgres \
	initdb -D /config/postgres --username=postgres

s6-setuidgid postgres \
	pg_upgrade \
	--old-datadir=/config/postgres.old \
	--new-datadir=/config/postgres \
	--old-bindir=/usr/lib/postgresql/14/bin \
	--new-bindir=/usr/lib/postgresql/15/bin

# this will remove the old postgres cluster, which includes postgres.old!!
# /config/postgres/delete_old_cluster.sh
```
This should work for amd64, but youll need to dig further to get it to work on arm, perhaps its possible to install pg14 from jammy and pg15 from lunar for arm. keep in mind that eventually postgres15 will no longer be available and this whole process will need to happen again... in due course. alternativly if that HA dockerfile is completly different, and you can find repos for postgres14 on arm and amd64, then you could probably just add them as apt sources and continue using pg14 for the time being...

**Comment by alexbelgium** [comment]
Thanks very much for your infos, and the proposed script to have both in parallel to support migration. Indeed I see that the best course of action would then be to develop an independent addon for Postgres that would be referred to in the addon... Migration would be too complex to perform so users would have to recreate their database, but at least it would be a long term solution. I'll continue looking at it. Thanks and great job with this omni-container project !

**Comment by hydazz** [comment]
> Thanks very much for your infos, and the proposed script to have both in parallel to support migration. Indeed I see that the best course of action would then be to develop an independent addon for Postgres that would be referred to in the addon... Migration would be too complex to perform so users would have to recreate their database, but at least it would be a long term solution. I'll continue looking at it. Thanks and great job with this omni-container project !

I have made a new branch `:jammy` which will continue to be updated with the latest version of immich until you/people find a way to migrate/update.

There are downsides, this branch will not generate thumbnails for heif photos, spamming the logs, and im sure there are other issues but pick ur poison, pin to downgraded version, or upgrade... each upstream immich update will probably break more things but a time 'buffer' does not hurt 😄

**Comment by ollioddi** [comment]
Okay im still having major issues with this change.

I have created a new Postgres 14 container in Unraid. I am able to use docker exec and `psql -h localhost -p 5432 -U postgres` to view the database.

I am however unable to connect to the database at all from outside the container.

Running this command on another machine on the same network yields `pg_isready -d postgres -h 192.168.20.135 -p 5432 -U postgres` -> `no response`.

Sometimes, the Postgres container logs `FATAL:  role "root" does not exist`.

It seems like the postgres container tries to use the wrong user?

Any suggestions?

**Comment by hydazz** [comment]
> Okay im still having major issues with this change.
> 
> I have created a new Postgres 14 container in Unraid. I am able to use docker exec and `psql -h localhost -p 5432 -U postgres` to view the database.
> 
> I am however unable to connect to the database at all from outside the container.
> 
> Running this command on another machine on the same network yields `pg_isready -d postgres -h 192.168.20.135 -p 5432 -U postgres` -> `no response`.
> 
> Sometimes, the Postgres container logs `FATAL: role "root" does not exist`.
> 
> It seems like the postgres container tries to use the wrong user?
> 
> Any suggestions?

does the postgres logs say `listening on 0.0.0.0`?

**Comment by ollioddi** [comment]
> > Okay im still having major issues with this change.
> > I have created a new Postgres 14 container in Unraid. I am able to use docker exec and `psql -h localhost -p 5432 -U postgres` to view the database.
> > I am however unable to connect to the database at all from outside the container.
> > Running this command on another machine on the same network yields `pg_isready -d postgres -h 192.168.20.135 -p 5432 -U postgres` -> `no response`.
> > Sometimes, the Postgres container logs `FATAL: role "root" does not exist`.
> > It seems like the postgres container tries to use the wrong user?
> > Any suggestions?
> 
> does the postgres logs say `listening on 0.0.0.0`?

First of all, thank you for being so quick to answer. Really appreciated when stuff is broken.

Here are my full logs from the postgres container upon restart: 

>27/05/2023 15.23.47
PostgreSQL Database directory appears to contain a database; Skipping initialization
27/05/2023 15.23.47
27/05/2023 15.23.47
2023-05-27 15:23:47.780 CEST [1] LOG:  starting PostgreSQL 14.8 (Debian 14.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
27/05/2023 15.23.47
2023-05-27 15:23:47.780 CEST [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
27/05/2023 15.23.47
2023-05-27 15:23:47.780 CEST [1] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
27/05/2023 15.23.47
2023-05-27 15:23:47.785 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
27/05/2023 15.23.47
2023-05-27 15:23:47.794 CEST [34] LOG:  database system was shut down at 2023-05-27 15:23:46 CEST
27/05/2023 15.23.47
2023-05-27 15:23:47.803 CEST [1] LOG:  database system is ready to accept connections

**Comment by hydazz** [comment]
you are having the same issue as above: https://github.com/imagegenius/docker-immich/issues/90#issuecomment-1562044094

**Comment by ollioddi** [comment]
@hydazz it was the exact same problem, all the way through. I apologize for not reading the other issues closer, and thank you again for the great support. Everything is up and running again without issues.

**Comment by RQZL** [comment]
Additional thoughtless mistakes I made in case anyone else encounters:
-Don't forget to delete the comment out -> # in postgresql.conf when switching to *.
-DB_HOSTNAME is just 172.19.0.5 or whatever your host ip is, not 172.19.0.5:5432
-Don't accidentally delete imagegenius/mods:universal-redis when deleting imagegenius/mods:universal-postgres.
Its a two left shoes day for me.

**Comment by hydazz** [comment]
seems like everythings smooth now
