### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8108

### ISSUE THREAD

**Issue by fdw** [imagegenius/docker-immich#93]
I've set up a completely new install using this Docker image and external Redis and Postgres. It seems to work, but I also have lots of similar errors trying to connect to `127.0.0.1:8108` in the logs. I've already disabled Typesense, but the errors still pop up.

I'm running on Arm64, if that is important. What other information do you need?

Not sure if it's related, but I see similar errors `Unable to run job handler: Error: connect ECONNREFUSED 127.0.0.1:3003` when uploading images. Should I open a separate issue for that?

**Comment by hydazz** [comment]
We havnt really tested the ARM image, I will spin up a native ARM VM and do some poking around, i assume that I will get the same errors and can work on them from there :)

**Comment by hydazz** [comment]
https://github.com/imagegenius/docker-immich/commit/d0b1d579de271ff49c862eb43495f2a7fbcb9118#diff-671cd03f0df8aa9eeb4ab60ebd313d338d1f361e77023e911791f2d1bae67c44R64 dammit

**Comment by hydazz** [comment]
try repulling once https://ci.imagegenius.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-immich/detail/main/195/pipeline finishes

**Comment by fdw** [comment]
Yup, works now. Thank you very much for the quick fix! 🙂
