### ISSUE TITLE
ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8108

### ISSUE THREAD

**Issue by friendlyFriend4000** [imagegenius/docker-immich#96]
I have updated my immich docker from v1.51.2 to 1.58 before reading up on the planned ubuntu version update. 
Since then I get the error shown in the title. From what I have gathered it has something to do with typesense(?).  I am on Unraid and so far I have tried to run it with `-e DISABLE_TYPESENSE=true`. I have tried to downgrade to v1.57 and then 1.51. But the error persist. Please advise.

**Comment by martabal** [comment]
Hello, it could be a corrupted file in typesense directory, just `rm -rf` its folder. On unraid, it should look like this : `rm -rf /mnt/user/appdata/immich/config/typesense`. So stop Immich, remove the typesense directory and restart Imimch. Don't worry, you can remove this directory without any problem, it will be re-constructed when Immich will restart

**Comment by friendlyFriend4000** [comment]
Thank you for your quick response. Deleting the typesense folder did not remove the error, the folder was empty anyway. What fixed it was downgrading even further to 1.50, before typesense was introduced. I gotta sort out how to update this container without breaking it again.

**Comment by martabal** [comment]
Does your cpu support AVX ?

**Comment by friendlyFriend4000** [comment]
Yes, my CPU does support AVX. I still couldn't update this immich image properly with because I am too stupid to figure out what's the issue and at this point I have lost my patience. I had to migrate back to the official docker stack becuase I am too stupid to figure out what's the issue and too tired at this point. The migration worked surprisingly well. Nonetheless I appreciate your help. Thank you.
