### ISSUE TITLE
TZ is not available in Asia region

### ISSUE THREAD

**Issue by czxinshui** [imagegenius/docker-immich#98]
TZ is not available in Asia region
TZ=Asia/Shanghai   invalid

**Comment by hydazz** [comment]
Could you provide more context?
- some logs
- where does it say `TZ=Asia/Shanghai invalid`?

**Comment by czxinshui** [comment]
> 你能提供更多的上下文吗？
> 
> * 一些日志
> * 它在哪里说`TZ=Asia/Shanghai invalid`？

The configuration file is written as TZ=Asia/Shanghai 
makefile is
  --name='immich'
   --net='bridge'
   --privileged=true
   -e TZ="America/Los_Angeles"
   -e HOST_OS="Unraid"

**Comment by czxinshui** [comment]
> where does it say `TZ=Asia/Shanghai invalid`??
> 
> I have set `TZ=Asia/Shanghai` and have no errors
> 
> You should also remove `--privileged=true`, its not needed!

According to your change is invalid
The time order of the pictures taken with the mobile phone camera is normal after uploading.
Use third-party mobile phone software, such as: check-in camera, watermark camera, screenshots, and download pictures. The chronological order of uploading these pictures will automatically change to tomorrow's time

**Comment by martabal** [comment]
From what I understand, this seems to be an upstream failure ? Can you test it with their dockers ?

**Comment by rexzhang** [comment]
> TZ is not available in Asia region TZ=Asia/Shanghai invalid

TZ 这个环境变量只是修改容器内部的设置.你可以在容器内shell执行 `export |grep TZ` 来确认

**Comment by martabal** [comment]
I'm not sure what you're asking, `TZ` env is not even used by Immich

**Comment by martabal** [comment]
My bad it's just a fallback

**Comment by martabal** [comment]
Can you share your configuration ?

**Comment by hydazz** [comment]
🤷
